// Shared helpers for the k6 load scripts: ES256 JWTs, private_key_jwt client
// assertions and DPoP proofs, all built with k6's WebCrypto so that every
// request carries a fresh, valid credential. Nothing here is a mock: an
// assertion or a proof with a reused `jti` is refused by the server (RFC 7523
// §3 item 7, RFC 9449 §11.1), which is why a static-body tool such as `oha`
// cannot drive the FAPI 2.0 endpoints past their first request.
//
// Everything is asynchronous because WebCrypto is; the scripts `await` it.

import encoding from 'k6/encoding';
import http from 'k6/http';

export const CLIENT_ASSERTION_TYPE = 'urn:ietf:params:oauth:client-assertion-type:jwt-bearer';

// --- encoding ---------------------------------------------------------------

export function b64url(bytes) {
  return encoding.b64encode(bytes.buffer ? bytes.buffer : bytes, 'rawurl');
}

function b64urlJson(value) {
  return encoding.b64encode(JSON.stringify(value), 'rawurl');
}

// A `jti` unique across VUs and iterations of one run, plus randomness so two
// runs against the same database do not collide inside a replay window.
export function jti(prefix) {
  const rand = new Uint8Array(12);
  crypto.getRandomValues(rand);
  return `${prefix}-${__VU}-${__ITER}-${b64url(rand)}`;
}

export function now() {
  return Math.floor(Date.now() / 1000);
}

// --- keys -------------------------------------------------------------------

// The client's own key, generated by gen-keys.sh as PKCS#8 DER. Read once per
// VU at init time (k6 only allows `open` there).
export async function importClientKey(der) {
  return crypto.subtle.importKey('pkcs8', der, { name: 'ECDSA', namedCurve: 'P-256' }, false, ['sign']);
}

// A fresh P-256 pair for DPoP. One per VU, as one per client instance.
export async function generateDpopKey() {
  const pair = await crypto.subtle.generateKey({ name: 'ECDSA', namedCurve: 'P-256' }, true, ['sign', 'verify']);
  const jwk = await crypto.subtle.exportKey('jwk', pair.publicKey);
  // RFC 7518 §6.2.1.2: a coordinate is the full field width — 32 bytes for
  // P-256 — so a value with a leading zero keeps it. k6's export drops it
  // (Go's big-integer bytes), which happens to one key in ~128 and made every
  // request of that VU an `invalid_dpop_proof`. Pad it back.
  return {
    privateKey: pair.privateKey,
    jwk: { kty: 'EC', crv: jwk.crv, x: fieldWidth(jwk.x, 32), y: fieldWidth(jwk.y, 32) },
  };
}

function fieldWidth(coordinate, bytes) {
  const raw = new Uint8Array(encoding.b64decode(coordinate, 'rawurl'));
  if (raw.length >= bytes) {
    return coordinate;
  }
  const padded = new Uint8Array(bytes);
  padded.set(raw, bytes - raw.length);
  return b64url(padded);
}

// --- JOSE -------------------------------------------------------------------

// ES256 compact serialisation. WebCrypto returns the raw `r || s` signature,
// which is exactly JWS's (RFC 7518 §3.4).
export async function signJwt(header, claims, privateKey) {
  const signingInput = `${b64urlJson(header)}.${b64urlJson(claims)}`;
  const signature = await crypto.subtle.sign(
    { name: 'ECDSA', hash: 'SHA-256' },
    privateKey,
    new TextEncoder().encode(signingInput),
  );
  return `${signingInput}.${b64url(new Uint8Array(signature))}`;
}

// RFC 7523 §3: a client assertion, audience the issuer (RFC 7523 §3 item 3,
// as the server reads it), single-use `jti`, short lifetime.
export async function clientAssertion(client, issuer, kid, privateKey) {
  const at = now();
  return signJwt(
    { alg: 'ES256', typ: 'JWT', kid },
    { iss: client, sub: client, aud: issuer, jti: jti('assertion'), iat: at, exp: at + 60 },
    privateKey,
  );
}

// RFC 9449 §4.2: a proof over one method and URL. `accessToken` adds `ath`
// for requests that present a token (§4.3 item 12).
export async function dpopProof(dpop, method, url, accessToken) {
  const claims = { jti: jti('proof'), htm: method, htu: url, iat: now() };
  if (accessToken) {
    const digest = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(accessToken));
    claims.ath = b64url(new Uint8Array(digest));
  }
  return signJwt({ typ: 'dpop+jwt', alg: 'ES256', jwk: dpop.jwk }, claims, dpop.privateKey);
}

// --- requests ---------------------------------------------------------------

// One `client_credentials` request with private_key_jwt and DPoP. Returns the
// k6 response; the scripts decide what to check. `resource` (RFC 8707) picks
// the audience; without it the tenant's default resource is the `aud`.
export async function clientCredentials(cfg, dpop, scope, tags, resource) {
  const url = `${cfg.issuer}/token`;
  const [assertion, proof] = await Promise.all([
    clientAssertion(cfg.clientId, cfg.issuer, cfg.kid, cfg.clientKey),
    dpopProof(dpop, 'POST', url),
  ]);
  const body = {
    grant_type: 'client_credentials',
    client_id: cfg.clientId,
    client_assertion_type: CLIENT_ASSERTION_TYPE,
    client_assertion: assertion,
  };
  if (scope) {
    body.scope = scope;
  }
  if (resource) {
    body.resource = resource;
  }
  const response = http.post(cfg.base + urlPath(url), body, {
    headers: { DPoP: proof, Host: cfg.host },
    tags,
  });
  if (response.status !== 200 && __ENV.DEBUG) {
    console.log(`refused ${response.status}: ${response.body}; proof ${proof.split('.')[1]}; assertion ${assertion.split('.')[1]}; now ${now()}`);
  }
  return response;
}

// The path-and-query of an absolute URL: requests go to `base` (where the
// process listens) while `htu` and `aud` name the issuer (what it believes it
// is), and the two differ when TLS is terminated elsewhere.
export function urlPath(url) {
  return url.replace(/^[a-z]+:\/\/[^/]+/, '');
}

// The authority of an absolute URL, which is the `Host` header the tenant is
// resolved by. k6 has no `URL` global, hence the hand-rolled split.
export function urlHost(url) {
  return url.replace(/^[a-z]+:\/\//, '').replace(/[/?#].*$/, '');
}

// Where to send requests, and as whom. Environment:
//   BASE_URL   the listener, default http://127.0.0.1:9443
//   ISSUER     the tenant issuer, default https://localhost:9443/t/load
//   CLIENT_ID  default load-client
//   KID        the `kid` in client.jwks.json, default load-key-1
export function configFromEnv(clientKey) {
  const issuer = __ENV.ISSUER || 'https://localhost:9443/t/load';
  return {
    base: __ENV.BASE_URL || 'http://127.0.0.1:9443',
    issuer,
    host: urlHost(issuer),
    clientId: __ENV.CLIENT_ID || 'load-client',
    kid: __ENV.KID || 'load-key-1',
    clientKey,
  };
}
