/** Two-phase native Keycloak and independent cryptographic RP for one owned selected client. */
import {readFileSync,writeFileSync,statSync} from 'node:fs';
import {createHash,createPublicKey,generateKeyPairSync,privateDecrypt,createDecipheriv,constants,randomBytes,verify} from 'node:crypto';
import {spawnSync} from 'node:child_process';
import {createServer} from 'node:https';
import {dirname,join} from 'node:path';
const {chromium}=await import(process.env.ASTERIUS_PLAYWRIGHT_MODULE??'../../e2e/node_modules/playwright-core/index.mjs');
process.umask(0o077);
function privateJson(path){if(statSync(path).mode&0o077)throw new Error('Private configuration required');return JSON.parse(readFileSync(path));}
const input=privateJson(process.argv[2]),fixture=privateJson(input.manifest),kc=privateJson(input.keycloakPrivate);
if(fixture.issuer!=='https://localhost:18447/t/e2e'||!/^ast_product_[a-f0-9]{32}$/.test(fixture.database)||!/^[a-f0-9-]{36}$/.test(fixture.client_id))throw new Error('Owned selected fixture required');
const issuer=fixture.issuer,origin=new URL(input.keycloakIssuer).origin,callback='https://localhost:18448/callback',pwd='urn:asterius:acr:pwd',cases=[];
function check(name,condition,details={}){if(!condition)throw new Error(name);cases.push({case:name,result:'pass',...details});}
function sql(query){const result=spawnSync('docker',['exec','-i',process.env.ASTERIUS_ACCEPTANCE_DB_CONTAINER,'psql','-U','asterius','-d',fixture.database,'-v','ON_ERROR_STOP=1','-At'],{input:query,encoding:'utf8'});if(result.status!==0)throw new Error('Owned fixture SQL refused');return result.stdout.trim();}
const original=sql("SELECT jwks::text FROM clients WHERE tenant_id='e2e' AND client_id='"+fixture.client_id+"';");
if(!original||JSON.parse(original).keys.some(k=>['d','p','q','dp','dq','qi','oth','k'].some(name=>name in k)))throw new Error('Owned public encryption source required');
const states=new Set(),callbacks=new Map();
const server=createServer({cert:readFileSync(fixture.ca_file),key:readFileSync(join(dirname(fixture.ca_file),'key.pem'))},(request,response)=>{const url=new URL(request.url,callback);if(url.pathname!=='/callback'||!states.has(url.searchParams.get('state'))){response.writeHead(400);response.end();return;}callbacks.set(url.searchParams.get('state'),url);response.writeHead(200,{'content-type':'text/plain'});response.end('Owned selected RP callback received');});
await new Promise(resolve=>server.listen(18448,'127.0.0.1',resolve));
const browser=await chromium.launch({headless:true,args:['--host-resolver-rules=MAP '+new URL(origin).hostname+' '+input.publicRelay]});
let stage='native RP setup',changed=false;
try{
 const admin=await fetch('http://127.0.0.1:9488/keycloak/realms/master/protocol/openid-connect/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'password',client_id:'admin-cli',username:kc.admin_username,password:kc.admin_password})});if(!admin.ok)throw new Error('Owned native administration refused');const token=(await admin.json()).access_token;
 async function native(method,path,body){const response=await fetch('http://127.0.0.1:9488/keycloak/admin/realms/asterius-protocol'+path,{method,headers:{authorization:'Bearer '+token,'content-type':'application/json'},body:body?JSON.stringify(body):undefined});if(!response.ok&&response.status!==409)throw new Error('Owned native configuration refused');return response;}
 const broker={alias:'asterius-ipsie',providerId:'oidc',enabled:true,trustEmail:true,firstBrokerLoginFlowAlias:'first broker login',config:{issuer,authorizationUrl:issuer+'/authorize?acr_values='+encodeURIComponent(pwd),tokenUrl:origin+'/ipsie-rp/token',userInfoUrl:origin+'/ipsie-rp/userinfo',jwksUrl:origin+'/ipsie-rp/jwks',clientId:fixture.client_id,clientSecret:fixture.secret,clientAuthMethod:'client_secret_basic',defaultScope:'openid profile email',validateSignature:'true',useJwksUrl:'true',pkceEnabled:'true',pkceMethod:'S256',disableUserInfo:'false',syncMode:'IMPORT'}};
 const registered=await native('POST','/identity-provider/instances',broker);if(registered.status===409)await native('PUT','/identity-provider/instances/asterius-ipsie',broker);
 await native('POST','/clients',{clientId:'owned-ipsie-app',enabled:true,protocol:'openid-connect',publicClient:true,standardFlowEnabled:true,redirectUris:[callback],attributes:{'pkce.code.challenge.method':'S256'}});
 const context=await browser.newContext({ignoreHTTPSErrors:true}),page=await context.newPage(),state=randomBytes(24).toString('base64url'),verifier=randomBytes(32).toString('base64url'),nativeUrl=new URL(input.keycloakIssuer+'/protocol/openid-connect/auth');states.add(state);
 for(const [key,value] of Object.entries({client_id:'owned-ipsie-app',redirect_uri:callback,response_type:'code',scope:'openid',state,nonce:randomBytes(24).toString('base64url'),code_challenge:createHash('sha256').update(verifier).digest('base64url'),code_challenge_method:'S256',kc_idp_hint:'asterius-ipsie'}))nativeUrl.searchParams.set(key,value);
 stage='native selected password RP';const metricsStart=readFileSync(input.relayMetrics,'utf8').trim().split('\n').filter(Boolean).length;
 await page.goto(nativeUrl.toString());await page.locator('input[name="username"]').fill('sweep@example.test');await page.locator('input[name="password"]').fill('correct horse battery staple');await page.getByRole('button',{name:'Sign in',exact:true}).click();
 const consent=page.getByRole('button',{name:'Allow',exact:true});await Promise.race([consent.waitFor({state:'visible',timeout:10000}).catch(()=>null),page.waitForURL(url=>url.port==='18448',{timeout:10000}).catch(()=>null)]);if(await consent.isVisible())await consent.click();
 const profile=page.locator('input[name="firstName"]');await Promise.race([profile.waitFor({state:'visible',timeout:10000}).catch(()=>null),page.waitForURL(url=>url.port==='18448',{timeout:10000}).catch(()=>null)]);
 if(await profile.isVisible()){const user=page.locator('input[name="username"]');if(await user.isEditable())await user.fill('owned-ipsie-'+randomBytes(4).toString('hex'));const email=page.locator('input[name="email"]');if(await email.isEditable())await email.fill('owned-ipsie-'+randomBytes(4).toString('hex')+'@example.invalid');await profile.fill('Owned');await page.locator('input[name="lastName"]').fill('Selected');await page.locator('button[type="submit"],input[type="submit"]').click();}
 await page.waitForURL(url=>url.port==='18448',{timeout:15000});check('native Keycloak selected password RP continuation',Boolean(callbacks.get(state)?.searchParams.get('code')));
 const metrics=readFileSync(input.relayMetrics,'utf8').trim().split('\n').filter(Boolean).slice(metricsStart).map(line=>JSON.parse(line));for(const path of ['/ipsie-rp/token','/ipsie-rp/userinfo'])check('native selected JWE '+path,metrics.some(m=>m.path===path&&m.status===200&&m.backend_tls_verified&&m.segments===5&&m.alg==='RSA-OAEP-256'&&m.enc==='A256GCM'));
 await context.close();stage='independent local RP encryption key';const key=generateKeyPairSync('rsa',{modulusLength:2048}),publicKey={...key.publicKey.export({format:'jwk'}),kid:'owned-independent-rp',use:'enc',alg:'RSA-OAEP-256'};
 const encoded=JSON.stringify({keys:[publicKey]}).replaceAll("'","''");sql("UPDATE clients SET jwks='"+encoded+"'::jsonb WHERE tenant_id='e2e' AND client_id='"+fixture.client_id+"';");changed=true;
 function decrypt(value){const segments=value.split('.');check('independent RP received compact JWE',segments.length===5);const header=JSON.parse(Buffer.from(segments[0],'base64url'));check('independent RP encryption algorithms pinned',header.alg==='RSA-OAEP-256'&&header.enc==='A256GCM');const cek=privateDecrypt({key:key.privateKey,padding:constants.RSA_PKCS1_OAEP_PADDING,oaepHash:'sha256'},Buffer.from(segments[1],'base64url')),decipher=createDecipheriv('aes-256-gcm',cek,Buffer.from(segments[2],'base64url'));decipher.setAAD(Buffer.from(segments[0]));decipher.setAuthTag(Buffer.from(segments[4],'base64url'));return Buffer.concat([decipher.update(Buffer.from(segments[3],'base64url')),decipher.final()]).toString();}
 const rp=await browser.newContext({ignoreHTTPSErrors:true}),metadata=await rp.request.get(issuer+'/.well-known/openid-configuration').then(r=>r.json()),jwks=await rp.request.get(metadata.jwks_uri).then(r=>r.json());
 check('selected discovery has attainable two-factor class',metadata.acr_values_supported.includes('urn:asterius:acr:passkey-uv'));
 function verified(value){const parts=value.split('.'),header=JSON.parse(Buffer.from(parts[0],'base64url')),claims=JSON.parse(Buffer.from(parts[1],'base64url')),jwk=jwks.keys.find(k=>k.kid===header.kid);check('independent RP nested ES256 signature verified',header.alg==='ES256'&&Boolean(jwk)&&verify('sha256',Buffer.from(parts.slice(0,2).join('.')),{key:createPublicKey({key:jwk,format:'jwk'}),dsaEncoding:'ieee-p1363'},Buffer.from(parts[2],'base64url')));return claims;}
 async function request(acr){const target=await rp.newPage(),requestState=randomBytes(24).toString('base64url'),requestVerifier=randomBytes(32).toString('base64url'),nonce=randomBytes(24).toString('base64url'),url=new URL(issuer+'/authorize');states.add(requestState);for(const [name,value] of Object.entries({client_id:fixture.client_id,redirect_uri:callback,response_type:'code',scope:'openid profile email',state:requestState,nonce,code_challenge:createHash('sha256').update(requestVerifier).digest('base64url'),code_challenge_method:'S256',acr_values:acr}))url.searchParams.set(name,value);await target.goto(url.toString());if(await target.locator('input[name="username"]').isVisible()){await target.locator('input[name="username"]').fill('sweep@example.test');await target.locator('input[name="password"]').fill('correct horse battery staple');await target.getByRole('button',{name:'Sign in',exact:true}).click();}const allow=target.getByRole('button',{name:'Allow',exact:true});await Promise.race([allow.waitFor({state:'visible',timeout:10000}).catch(()=>null),target.waitForURL(u=>u.port==='18448',{timeout:10000}).catch(()=>null)]);if(await allow.isVisible())await allow.click();await target.waitForURL(u=>u.port==='18448',{timeout:15000});return {returned:callbacks.get(requestState),verifier:requestVerifier,nonce};}
 stage='selected independent password claim verification';const success=await request(pwd);check('selected requested password ACR returned plain code',Boolean(success.returned?.searchParams.get('code'))&&!success.returned.searchParams.has('response'));
 const issued=await rp.request.post(issuer+'/token',{headers:{authorization:'Basic '+Buffer.from(fixture.client_id+':'+fixture.secret).toString('base64')},form:{grant_type:'authorization_code',code:success.returned.searchParams.get('code'),redirect_uri:callback,code_verifier:success.verifier}});check('selected independent RP code exchange',issued.status()===200);const tokens=await issued.json(),claims=verified(decrypt(tokens.id_token));
 check('selected token issuer audience and nonce exact',claims.iss===issuer&&claims.aud===fixture.client_id&&claims.nonce===success.nonce);
 check('selected session deadline is original JSON integer at least 300 seconds',Number.isInteger(claims.iat)&&Number.isInteger(claims.session_expiry)&&claims.session_expiry>=claims.iat+300,{minimum_seconds:300,observed_seconds:claims.session_expiry-claims.iat});
 check('selected password assurance truthful',claims.acr===pwd&&Array.isArray(claims.amr)&&claims.amr.includes('pwd')&&!claims.amr.includes('mfa'),{acr:claims.acr,amr:claims.amr});
 const userinfo=await rp.request.get(issuer+'/userinfo',{headers:{authorization:'Bearer '+tokens.access_token}});check('selected independent encrypted UserInfo',userinfo.status()===200);const identity=verified(decrypt(await userinfo.text()));check('selected UserInfo subject bound to ID token',identity.sub===claims.sub);
 stage='unsupported selected ACR refusal';const refused=await request('urn:owned:unsupported-acr');check('selected unsupported ACR refused without authorization code',refused.returned?.searchParams.get('error')==='unmet_authentication_requirements'&&!refused.returned.searchParams.has('code'),{observed_error:refused.returned.searchParams.get('error')});
 sql("UPDATE clients SET jwks='"+original.replaceAll("'","''")+"'::jsonb WHERE tenant_id='e2e' AND client_id='"+fixture.client_id+"';");changed=false;check('owned native encryption key restored',sql("SELECT jwks::text FROM clients WHERE tenant_id='e2e' AND client_id='"+fixture.client_id+"';")===original);
 const result={status:'pass',date:'2026-10-08',implementation:'Keycloak26.7.4 + native Node crypto independent RP',runtime_revision:fixture.runtime_revision,asterius_binary_sha256:fixture.binary_sha256,cases,formal_conformance:false,limits:['Owned isolated selected client deployment; not certification.','Two-factor class attainable in configuration; hardware MFA execution not claimed.','No federation ACR invention; password flow supplies pwd.','Native Keycloak public encryption source restored after independent RP key rotation.']};writeFileSync(input.evidence,JSON.stringify(result,null,2),{mode:0o600});console.info(JSON.stringify({status:'pass',checks:cases.length}));
}catch(error){console.error(JSON.stringify({status:'failed',stage,type:error.name,checks:cases.length,reason:/^(Owned|selected|native|independent)/.test(error.message)?error.message:'browser-operation'}));process.exitCode=1;}finally{try{if(changed)sql("UPDATE clients SET jwks='"+original.replaceAll("'","''")+"'::jsonb WHERE tenant_id='e2e' AND client_id='"+fixture.client_id+"';");}finally{await browser.close();await new Promise(resolve=>server.close(resolve));}}
