/** Native Keycloak -> guarded Asterius callback; secrets and transaction URLs stay private. */
import {readFileSync,writeFileSync,statSync} from 'node:fs';
import {createHash,createPublicKey,randomBytes,verify} from 'node:crypto';
import {spawnSync} from 'node:child_process';
import {createServer} from 'node:https';
import {dirname,join} from 'node:path';
const {chromium}=await import(process.env.ASTERIUS_PLAYWRIGHT_MODULE??'../../e2e/node_modules/playwright-core/index.mjs');
process.umask(0o077);
const file=process.argv[2];if(statSync(file).mode&0o077)throw new Error('Private inputs required');
const input=JSON.parse(readFileSync(file,'utf8')),fixture=JSON.parse(readFileSync(input.manifest,'utf8')),kc=JSON.parse(readFileSync(input.keycloakPrivate,'utf8'));
if(fixture.issuer!=='https://localhost:18444/t/e2e'||!/^ast_product_[a-f0-9]{32}$/.test(fixture.database))throw new Error('Owned fixture required');
const issuer=fixture.issuer,origin=new URL(input.keycloakIssuer).origin,provider='keycloak-fixture',callback=issuer+'/oidc/upstream/callback/'+provider;
let stage='bootstrap',diagnosticPage,profileSubmitted=false;const cases=[];
function check(name,condition,observed={}){if(!condition)throw new Error(name);cases.push({case:name,result:'pass',...observed});writeFileSync(input.evidence,JSON.stringify({status:'in_progress',cases,asterius_binary_sha256:fixture.binary_sha256,runtime_revision:fixture.runtime_revision,formal_conformance:false},null,2),{mode:0o600});}
function snapshot(){
 const r=spawnSync('docker',['exec','-i',process.env.ASTERIUS_ACCEPTANCE_DB_CONTAINER,'psql','-U','asterius','-d',fixture.database,'-v','ON_ERROR_STOP=1','-At'],{input:"SELECT (SELECT count(*) FROM sessions WHERE tenant_id='e2e') || ':' || (SELECT count(*) FROM oidc_identity_bindings WHERE tenant_id='e2e') || ':' || (SELECT count(*) FROM users WHERE tenant_id='e2e');",encoding:'utf8'});
 if(r.status!==0)throw new Error('Owned snapshot unavailable');return r.stdout.trim();
}
const expectedStates=new Set(),callbackRecords=new Map(),servers=[];
for(const port of [18445,18446]){const server=createServer({cert:readFileSync(fixture.ca_file),key:readFileSync(join(dirname(fixture.ca_file),'key.pem'))},(request,response)=>{const url=new URL(request.url,'https://localhost:'+port);if(url.pathname!=='/callback'||!expectedStates.has(url.searchParams.get('state'))){response.writeHead(400);response.end();return;}callbackRecords.set(url.searchParams.get('state'),url.toString());response.writeHead(200,{'content-type':'text/plain'});response.end('Owned RP callback received');});await new Promise(resolve=>server.listen(port,'127.0.0.1',resolve));servers.push(server);}
const browser=await chromium.launch({headless:true,args:['--host-resolver-rules=MAP '+new URL(origin).hostname+' '+input.publicRelay]});
try{
 const admin=await browser.newContext({ignoreHTTPSErrors:true}),page=await admin.newPage();
 await page.goto(issuer+'/admin/');await page.locator('input[name="username"]').fill('sweep@example.test');await page.locator('input[name="password"]').fill('correct horse battery staple');await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.waitForURL(url=>url.pathname.endsWith('/admin/'));
 async function api(method,path,body){return page.evaluate(async({method,path,body})=>{const session=await fetch('api/v1/session').then(r=>r.json());const response=await fetch('api/v1'+path,{method,headers:{'content-type':'application/json','x-csrf-token':session.csrf_token,...(method==='POST'?{'idempotency-key':crypto.randomUUID()}: {})},body:body===undefined?undefined:JSON.stringify(body)});return {status:response.status,body:response.status===204?{}:await response.json()};},{method,path,body});}
 stage='guarded provider setup';
 const setup=await api('PUT','/oidc/providers',{id:provider,name:'Owned native Keycloak',issuer:input.keycloakIssuer,client_id:kc.client_id,client_secret:kc.client_secret,enabled:true,allow_registration:false});check('guarded native Keycloak provider registration',[200,201].includes(setup.status));
 const tokenResponse=await fetch('http://127.0.0.1:9488/keycloak/realms/master/protocol/openid-connect/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'password',client_id:'admin-cli',username:kc.admin_username,password:kc.admin_password})});if(!tokenResponse.ok)throw new Error('Owned Keycloak administration refused');const token=(await tokenResponse.json()).access_token;
 const users=await fetch('http://127.0.0.1:9488/keycloak/admin/realms/asterius-protocol/users?username='+encodeURIComponent(kc.user)+'&exact=true',{headers:{authorization:'Bearer '+token}}).then(r=>r.json());if(users.length!==1)throw new Error('Owned native subject missing');
 async function kcAdmin(path,body){const r=await fetch('http://127.0.0.1:9488/keycloak/admin/realms/asterius-protocol'+path,{method:'POST',headers:{authorization:'Bearer '+token,'content-type':'application/json'},body:JSON.stringify(body)});if(r.status===409&&path==='/identity-provider/instances'){const existing=await fetch('http://127.0.0.1:9488/keycloak/admin/realms/asterius-protocol'+path+'/'+encodeURIComponent(body.alias),{method:'PUT',headers:{authorization:'Bearer '+token,'content-type':'application/json'},body:JSON.stringify(body)});if(!existing.ok)throw new Error('Owned native RP update refused');return existing.status;}if(r.status===409&&path==='/clients'){const existing=await fetch('http://127.0.0.1:9488/keycloak/admin/realms/asterius-protocol/clients?clientId='+encodeURIComponent(body.clientId),{headers:{authorization:'Bearer '+token}}).then(r=>r.json());if(existing.length!==1)throw new Error('Owned native RP duplicate ambiguous');return 200;}if(!r.ok)throw new Error('Owned native RP configuration refused');return r.status;}
 const linked=await api('PUT','/users/3f1d5c2a-0000-4000-8000-000000000001/oidc-bindings',{provider_id:provider,issuer:input.keycloakIssuer,upstream_subject:users[0].id});const existing=linked.status===409?await api('GET','/users/3f1d5c2a-0000-4000-8000-000000000001/oidc-bindings'):null;check('guarded exact upstream binding',[200,201].includes(linked.status)||(existing?.status===200&&existing.body.bindings.some(b=>b.provider_id===provider&&b.issuer===input.keycloakIssuer&&b.upstream_subject===users[0].id)));
 async function transaction(selected=provider,label='Owned native Keycloak'){
  const context=await browser.newContext({ignoreHTTPSErrors:true}),target=await context.newPage(),verifier=randomBytes(32).toString('base64url');
  const url=new URL(issuer+'/authorize');for(const [key,value] of Object.entries({client_id:fixture.client_id,redirect_uri:'https://localhost:18445/callback',response_type:'code',scope:'openid email',state:randomBytes(24).toString('base64url'),nonce:randomBytes(24).toString('base64url'),code_challenge:createHash('sha256').update(verifier).digest('base64url'),code_challenge_method:'S256'}))url.searchParams.set(key,value);
  expectedStates.add(url.searchParams.get('state'));let held,capturedResolve;const captured=new Promise(resolve=>{capturedResolve=resolve;});await target.route('**/oidc/upstream/callback/'+selected+'**',async route=>{held=route.request().url();capturedResolve();await route.fulfill({status:200,contentType:'text/plain',body:'Owned pending callback captured'});});
  await target.route('**/keycloak/realms/asterius-protocol/login-actions/authenticate**',async route=>{if(route.request().method()!=='POST'){await route.continue();return;}const response=await route.fetch({maxRedirects:0}),location=response.headers().location;if(location&&new URL(location).pathname.endsWith('/oidc/upstream/callback/'+selected)){held=location;capturedResolve();const headers={...response.headers()};delete headers.location;await route.fulfill({response,status:200,headers,body:'Owned native callback captured before redirect'});}else await route.fulfill({response});});
  stage='native RP authorization';await target.goto(url.toString());stage='native provider link';await target.getByRole('link',{name:'Continue with '+label,exact:true}).click();
  stage='native Keycloak credentials';await target.locator('input[name="username"]').fill(kc.user);await target.locator('input[name="password"]').fill(kc.password);await target.locator('button[type="submit"], input[type="submit"]').click();
  stage='native Keycloak callback';await Promise.race([captured,new Promise((_,reject)=>setTimeout(()=>reject(new Error('Native upstream callback absent')),10000))]);if(!held||new URL(held).origin!==new URL(callback).origin)throw new Error('Native upstream callback absent');
  await target.unroute('**/oidc/upstream/callback/'+selected+'**');await target.unroute('**/keycloak/realms/asterius-protocol/login-actions/authenticate**');if(selected==='controlled-peer'){const controlled=new URL(held);controlled.searchParams.set('iss',input.controlledIssuer);held=controlled.toString();}return {context,target,held,verifier,state:url.searchParams.get('state')};
 }
 if(!input.jweOnly){
 stage='native pending transaction';const first=await transaction(),other=await browser.newContext({ignoreHTTPSErrors:true}),otherPage=await other.newPage();
 let before=snapshot();const transplanted=await otherPage.goto(first.held);check('foreign browser callback refused',transplanted.status()===400&&snapshot()===before,{expected_status:400,observed_status:transplanted.status(),mutation:false});
 const unknown=new URL(first.held);unknown.searchParams.set('state',randomBytes(32).toString('base64url'));before=snapshot();const missing=await first.target.goto(unknown.toString());check('unknown state refused without session or binding',missing.status()===400&&snapshot()===before,{expected_status:400,observed_status:missing.status(),mutation:false});
 stage='native upstream completion';let downstream;
 const completion=await first.target.goto(first.held);if(completion.status()>=400)throw new Error('Native upstream completion HTTP '+completion.status());const allow=first.target.getByRole('button',{name:'Allow',exact:true});await Promise.race([allow.waitFor({state:'visible',timeout:10000}).catch(()=>null),first.target.waitForURL(url=>url.port==='18445',{timeout:10000}).catch(()=>null)]);if(await allow.isVisible())await allow.click();await first.target.waitForURL(url=>url.port==='18445',{timeout:15000});downstream=callbackRecords.get(first.state);check('native downstream authorization continuation',Boolean(downstream));
 const code=new URL(downstream).searchParams.get('code');if(!code)throw new Error('Downstream code absent');
 const tokenResult=await first.context.request.post(issuer+'/token',{headers:{authorization:'Basic '+Buffer.from(fixture.client_id+':'+fixture.secret).toString('base64')},form:{grant_type:'authorization_code',code,redirect_uri:'https://localhost:18445/callback',code_verifier:first.verifier}});check('real downstream RP code exchange',tokenResult.status()===200);
 const issued=await tokenResult.json(),metadata=await first.context.request.get(issuer+'/.well-known/openid-configuration').then(r=>r.json()),jwks=await first.context.request.get(metadata.jwks_uri).then(r=>r.json()),parts=issued.id_token.split('.'),header=JSON.parse(Buffer.from(parts[0],'base64url')),claims=JSON.parse(Buffer.from(parts[1],'base64url')),key=jwks.keys.find(k=>k.kid===header.kid);
 check('downstream ES256 identity token verified',header.alg==='ES256'&&claims.iss===issuer&&claims.aud===fixture.client_id&&verify('sha256',Buffer.from(parts.slice(0,2).join('.')),{key:createPublicKey({key,format:'jwk'}),dsaEncoding:'ieee-p1363'},Buffer.from(parts[2],'base64url')));
 stage='callback replay';before=snapshot();const replay=await first.target.goto(first.held);check('consumed state replay refused without session or binding',replay.status()===400&&snapshot()===before,{expected_status:400,observed_status:replay.status(),mutation:false});
 stage='callback issuer mismatch';const mixup=await transaction(),mixed=new URL(mixup.held);mixed.searchParams.set('iss','https://untrusted.example');before=snapshot();const mixedResponse=await mixup.target.goto(mixed.toString());check('mismatched authorization issuer refused without session or binding',mixedResponse.status()===400&&snapshot()===before,{expected_status:400,observed_status:mixedResponse.status(),mutation:false});
 stage='expired pending callback';const expired=await transaction(),expiredState=new URL(expired.held).searchParams.get('state'),digest=createHash('sha256').update(expiredState).digest('hex');
 const aged=spawnSync('docker',['exec','-i',process.env.ASTERIUS_ACCEPTANCE_DB_CONTAINER,'psql','-U','asterius','-d',fixture.database,'-v','ON_ERROR_STOP=1','-At'],{input:`UPDATE oidc_upstream_pending SET expires_at=now()-interval '1 minute' WHERE tenant_id='e2e' AND state_digest='${digest}';`,encoding:'utf8'});if(aged.status!==0)throw new Error('Owned pending expiry setup refused');before=snapshot();const expiredResponse=await expired.target.goto(expired.held);check('expired pending callback refused without session or binding',expiredResponse.status()===400&&snapshot()===before,{expected_status:400,observed_status:expiredResponse.status(),mutation:false});

 stage='controlled independent fault fixture setup';
 const controlledSetup=await api('PUT','/oidc/providers',{id:'controlled-peer',name:'Controlled OIDC peer',issuer:input.controlledIssuer,client_id:kc.client_id,client_secret:kc.client_secret,enabled:true,allow_registration:false});check('guarded controlled provider registration',[200,201].includes(controlledSetup.status));
 const mode=(fault='normal',active_key=0)=>writeFileSync(input.controlledMode,JSON.stringify({mode:fault,active_key}),{mode:0o600});
 mode();const unlinked=await api('DELETE','/users/3f1d5c2a-0000-4000-8000-000000000001/oidc-bindings',{provider_id:'controlled-peer',issuer:input.controlledIssuer,upstream_subject:users[0].id});if(![200,204,404].includes(unlinked.status))throw new Error('Owned controlled binding cleanup refused');const unmapped=await transaction('controlled-peer','Controlled OIDC peer');before=snapshot();const unmappedResponse=await unmapped.target.goto(unmapped.held);console.info(JSON.stringify({case:'unmapped-provider',status:unmappedResponse.status(),unchanged:snapshot()===before}));check('identical native subject cannot cross provider ownership',unmappedResponse.status()===400&&snapshot()===before&&!callbackRecords.has(unmapped.state),{expected_status:400,observed_status:unmappedResponse.status(),mutation:false});
 const bound=await api('PUT','/users/3f1d5c2a-0000-4000-8000-000000000001/oidc-bindings',{provider_id:'controlled-peer',issuer:input.controlledIssuer,upstream_subject:users[0].id});const controlledExisting=bound.status===409?await api('GET','/users/3f1d5c2a-0000-4000-8000-000000000001/oidc-bindings'):null;check('guarded exact controlled provider binding',[200,201].includes(bound.status)||(controlledExisting?.status===200&&controlledExisting.body.bindings.some(b=>b.provider_id==='controlled-peer'&&b.issuer===input.controlledIssuer&&b.upstream_subject===users[0].id)));
 async function controlledPositive(name){const tx=await transaction('controlled-peer','Controlled OIDC peer');const completion=await tx.target.goto(tx.held);if(completion.status()>=400)throw new Error('Owned controlled completion HTTP '+completion.status());const consent=tx.target.getByRole('button',{name:'Allow',exact:true});await Promise.race([consent.waitFor({state:'visible',timeout:10000}).catch(()=>null),tx.target.waitForURL(url=>url.port==='18445',{timeout:10000}).catch(()=>null)]);if(await consent.isVisible())await consent.click();await tx.target.waitForURL(url=>url.port==='18445',{timeout:15000});const returned=callbackRecords.get(tx.state);check(name,Boolean(returned&&new URL(returned).searchParams.get('code')));return tx;}
 await controlledPositive('independently signed controlled identity accepted');
 for(const fault of ['expired','forged','wrong_issuer','wrong_nonce','wrong_subject','token_outage','jwks_outage']){stage='controlled '+fault;mode(fault,fault==='jwks_outage'?1:0);const tx=await transaction('controlled-peer','Controlled OIDC peer');before=snapshot();const response=await tx.target.goto(tx.held);console.info(JSON.stringify({case:fault,status:response.status(),unchanged:snapshot()===before}));check('controlled '+fault+' refused without user session or binding',response.status()===(fault.endsWith('outage')?503:400)&&snapshot()===before&&!callbackRecords.has(tx.state),{expected_status:fault.endsWith('outage')?503:400,observed_status:response.status(),mutation:false});mode();}
 mode('normal',1);await controlledPositive('independent peer signing key rotation accepted');mode();await controlledPositive('independent peer recovered after token and JWKS outages');
 const cross=await transaction('controlled-peer','Controlled OIDC peer'),crossUrl=new URL(cross.held);crossUrl.pathname=crossUrl.pathname.replace('/t/e2e/','/t/e2e-webauthn/');before=snapshot();const crossResponse=await cross.target.goto(crossUrl.toString());check('cross tenant pending callback refused without mutation',[400,404].includes(crossResponse.status())&&snapshot()===before,{observed_status:crossResponse.status(),mutation:false});

 stage='native Keycloak signing key rotation';
 const oldNativeActive=await fetch('http://127.0.0.1:9488/keycloak/admin/realms/asterius-protocol/keys',{headers:{authorization:'Bearer '+token}}).then(r=>r.json());
 const oldNativeKeys=await fetch('http://127.0.0.1:9488/keycloak/realms/asterius-protocol/protocol/openid-connect/certs').then(r=>r.json());
 const realm=await fetch('http://127.0.0.1:9488/keycloak/admin/realms/asterius-protocol',{headers:{authorization:'Bearer '+token}}).then(r=>r.json());
 await kcAdmin('/components',{name:'owned-rotation-'+Date.now(),providerId:'ecdsa-generated',providerType:'org.keycloak.keys.KeyProvider',parentId:realm.id,config:{priority:[String(Math.max(300,...oldNativeActive.keys.map(k=>Number(k.providerPriority)||0))+100)],enabled:['true'],active:['true'],ecdsaEllipticCurveKey:['P-256'],algorithm:['ES256']}});
 const newNativeActive=await fetch('http://127.0.0.1:9488/keycloak/admin/realms/asterius-protocol/keys',{headers:{authorization:'Bearer '+token}}).then(r=>r.json());check('native Keycloak active ES256 signing key changed',Boolean(newNativeActive.active?.ES256&&newNativeActive.active.ES256!==oldNativeActive.active?.ES256));
 const rotatedNativeKeys=await fetch('http://127.0.0.1:9488/keycloak/realms/asterius-protocol/protocol/openid-connect/certs').then(r=>r.json());check('native Keycloak published newly generated signing key',rotatedNativeKeys.keys.some(k=>k.use==='sig'&&k.alg==='ES256'&&!oldNativeKeys.keys.some(old=>old.kid===k.kid)));
 const rotated=await transaction();const rotateResponse=await rotated.target.goto(rotated.held);if(rotateResponse.status()>=400)throw new Error('Native rotated callback HTTP '+rotateResponse.status());const rotateAllow=rotated.target.getByRole('button',{name:'Allow',exact:true});await Promise.race([rotateAllow.waitFor({state:'visible',timeout:10000}).catch(()=>null),rotated.target.waitForURL(url=>url.port==='18445',{timeout:10000}).catch(()=>null)]);if(await rotateAllow.isVisible())await rotateAllow.click();await rotated.target.waitForURL(url=>url.port==='18445',{timeout:15000});check('native Keycloak signing key rotation continued to downstream RP',Boolean(callbackRecords.get(rotated.state)&&new URL(callbackRecords.get(rotated.state)).searchParams.get('code')));
 }
 if(input.skipEncrypted){writeFileSync(input.evidence,JSON.stringify({status:'pass',implementation:'Keycloak26.7.4',cases,asterius_binary_sha256:fixture.binary_sha256,runtime_revision:fixture.runtime_revision,native_keycloak:true,native_encrypted_id_token:false,native_encrypted_userinfo:false,controlled_token_faults:!input.jweOnly,formal_conformance:false},null,2),{mode:0o600});console.info(JSON.stringify({status:'controlled_pass',cases:cases.length}));process.exitCode=0;}else{
 stage='native encrypted enterprise RP setup';
 const keys=await fetch('http://127.0.0.1:9488/keycloak/realms/asterius-protocol/protocol/openid-connect/certs').then(r=>r.json());
 const encryptionKeys=keys.keys.filter(k=>k.use==='enc'&&k.alg==='RSA-OAEP-256');if(encryptionKeys.length!==1)throw new Error('One native encryption key required');
 const jweClient=await api('POST','/clients',{client_name:'Owned Keycloak encrypted RP',compliance_profile:'oidc',application_type:'web',token_endpoint_auth_method:'client_secret_basic',redirect_uris:[origin+'/keycloak/realms/asterius-protocol/broker/asterius-encrypted/endpoint'],grant_types:['authorization_code'],response_types:['code'],scope:'openid profile email',id_token_signed_response_alg:'ES256',userinfo_signed_response_alg:'ES256',id_token_encrypted_response_alg:'RSA-OAEP-256',id_token_encrypted_response_enc:'A256GCM',userinfo_encrypted_response_alg:'RSA-OAEP-256',userinfo_encrypted_response_enc:'A256GCM',jwks:{keys:encryptionKeys},dpop_bound_access_tokens:false});
 console.info(JSON.stringify({debug:'encrypted-registration',status:jweClient.status,code:jweClient.body.error?.code,message:jweClient.status!==201?jweClient.body.error?.message:undefined}));check('guarded encrypted RP client registration',jweClient.status===201&&Boolean(jweClient.body.client_id));
 const resource=await api('PUT','/resource-servers/'+encodeURIComponent(issuer),{scopes:['openid','profile','email'],default_token_lifetime_seconds:60});check('guarded identity-only resource registration',[200,201].includes(resource.status));
 const assignment=await api('PUT','/clients/'+encodeURIComponent(jweClient.body.client_id)+'/resources',{resources:[issuer]});check('guarded RP issuer audience assignment',assignment.status===200);
 await kcAdmin('/identity-provider/instances',{alias:'asterius-encrypted',providerId:'oidc',enabled:true,trustEmail:true,firstBrokerLoginFlowAlias:'first broker login',config:{issuer,authorizationUrl:issuer+'/authorize',tokenUrl:origin+'/asterius-rp/token',userInfoUrl:origin+'/asterius-rp/userinfo',jwksUrl:origin+'/asterius-rp/jwks',clientId:jweClient.body.client_id,clientSecret:jweClient.body.client_secret,clientAuthMethod:'client_secret_basic',defaultScope:'openid profile email',validateSignature:'true',useJwksUrl:'true',pkceEnabled:'true',pkceMethod:'S256',disableUserInfo:'false',syncMode:'IMPORT',updateProfileFirstLoginMode:'off'}});
 await kcAdmin('/clients',{clientId:'owned-encrypted-app',enabled:true,protocol:'openid-connect',publicClient:true,standardFlowEnabled:true,redirectUris:['https://localhost:18446/callback'],attributes:{'pkce.code.challenge.method':'S256'}});
 stage='native encrypted enterprise RP login';const metricsStart=readFileSync(input.relayMetrics,'utf8').trim().split('\n').filter(Boolean).length;
 const rpContext=await browser.newContext({ignoreHTTPSErrors:true}),rpPage=await rpContext.newPage(),rpVerifier=randomBytes(32).toString('base64url');let rpCallback;diagnosticPage=rpPage;
 const rpUrl=new URL(input.keycloakIssuer+'/protocol/openid-connect/auth');for(const [key,value] of Object.entries({client_id:'owned-encrypted-app',redirect_uri:'https://localhost:18446/callback',response_type:'code',scope:'openid',state:randomBytes(24).toString('base64url'),nonce:randomBytes(24).toString('base64url'),code_challenge:createHash('sha256').update(rpVerifier).digest('base64url'),code_challenge_method:'S256',kc_idp_hint:'asterius-encrypted'}))rpUrl.searchParams.set(key,value);
 expectedStates.add(rpUrl.searchParams.get('state'));await rpPage.goto(rpUrl.toString());await rpPage.locator('input[name="username"]').fill('sweep@example.test');await rpPage.locator('input[name="password"]').fill('correct horse battery staple');await rpPage.getByRole('button',{name:'Sign in',exact:true}).click();
 const rpAllow=rpPage.getByRole('button',{name:'Allow',exact:true});await Promise.race([rpAllow.waitFor({state:'visible',timeout:10000}).catch(()=>null),rpPage.waitForURL(url=>url.port==='18446',{timeout:10000}).catch(()=>null)]);if(await rpAllow.isVisible())await rpAllow.click();
 // Native first-broker profile completion is distinct from ciphertext validation.
 const profile=rpPage.locator('input[name="firstName"]');await Promise.race([profile.waitFor({state:'visible',timeout:10000}).catch(()=>null),rpPage.waitForURL(url=>url.port==='18446',{timeout:10000}).catch(()=>null)]);if(await profile.isVisible()){const email=rpPage.locator('input[name="email"]');if(await email.isVisible()&&!await email.inputValue())await email.fill('owned-asterius-jwe@example.invalid');const username=rpPage.locator('input[name="username"]');if(await username.isEditable())await username.fill('owned-asterius-jwe-'+randomBytes(4).toString('hex'));profileSubmitted=true;await profile.fill('Owned');await rpPage.locator('input[name="lastName"]').fill('Fixture');await rpPage.locator('button[type="submit"], input[type="submit"]').click();}
 await rpPage.waitForURL(url=>url.port==='18446',{timeout:15000});rpCallback=callbackRecords.get(rpUrl.searchParams.get('state'));check('native Keycloak decrypted encrypted ID token and UserInfo',Boolean(new URL(rpCallback).searchParams.get('code')));
 const metrics=readFileSync(input.relayMetrics,'utf8').trim().split('\n').filter(Boolean).slice(metricsStart).map(line=>JSON.parse(line));
 for(const path of ['/asterius-rp/token','/asterius-rp/userinfo'])check('actual JWE ciphertext '+path,metrics.some(m=>m.path===path&&m.status===200&&m.backend_tls_verified&&m.segments===5&&m.alg==='RSA-OAEP-256'&&m.enc==='A256GCM'));
 const result={status:'pass',implementation:'Keycloak26.7.4',cases,asterius_binary_sha256:fixture.binary_sha256,runtime_revision:fixture.runtime_revision,native_keycloak:true,native_encrypted_id_token:true,native_encrypted_userinfo:true,controlled_token_faults:!input.jweOnly,formal_conformance:false};writeFileSync(input.evidence,JSON.stringify(result,null,2),{mode:0o600});console.info(JSON.stringify({status:'pass',cases:cases.length,native_keycloak:true,controlled_token_faults:!input.jweOnly}));
}
}catch(error){console.error(JSON.stringify({profileSubmitted}));if(diagnosticPage)console.error(JSON.stringify(await diagnosticPage.evaluate(()=>({path:location.pathname,invalid:[...document.querySelectorAll('input')].filter(e=>!e.checkValidity()||e.getAttribute('aria-invalid')==='true').map(e=>e.name),empty:[...document.querySelectorAll('input')].filter(e=>!e.value).map(e=>e.name),errorCodes:[...document.querySelectorAll('[id*=error]')].map(e=>e.id).filter(n=>/^[A-Za-z0-9_-]{1,60}$/.test(n)),inputs:[...document.querySelectorAll('input')].map(e=>e.name).filter(n=>/^[A-Za-z_-]{1,30}$/.test(n)),buttons:[...document.querySelectorAll('button,input[type=submit]')].map(e=>['Submit','Continue','Sign in','Yes','No','Update','Link account','Add to existing account','Review profile','Back to application'].includes(e.innerText)?e.innerText:'other')})).catch(()=>({diagnostic:'unavailable'}))));console.error('KEYCLOAK_CHECK_FAILED stage='+stage+' type='+error.name+' network='+(error.message.match(/net::[A-Z_]+/)?.[0]??'none')+' checks='+cases.length+' reason='+(/^(Owned|Native|native|guarded|foreign|unknown|consumed|real|downstream|mismatched|expired|actual|One)/.test(error.message)?error.message:'browser-operation'));process.exitCode=1;}finally{await browser.close();for(const server of servers)await new Promise(resolve=>server.close(resolve));}
