/** Actual guarded lifecycle -> public independent Command RP. No token or account identity output. */
import {readFileSync,writeFileSync,statSync} from 'node:fs';
import {createHash,createPublicKey,randomBytes,verify} from 'node:crypto';
import {createServer} from 'node:https';
import {spawnSync} from 'node:child_process';
import {dirname,join} from 'node:path';
import {peer} from './provider_command_peer.mjs';
import {DpopClient} from '../entra-scim-adapter/adapter.mjs';
const {chromium}=await import(process.env.ASTERIUS_PLAYWRIGHT_MODULE??'../../e2e/node_modules/playwright-core/index.mjs');
process.umask(0o077);
function privateJson(path){if(statSync(path).mode&0o077)throw new Error('Private configuration required');return JSON.parse(readFileSync(path));}
const input=privateJson(process.argv[2]),fixture=privateJson(input.manifest);
if(fixture.issuer!=='https://localhost:18444/t/e2e'||!/^ast_product_[a-f0-9]{32}$/.test(fixture.database))throw new Error('Owned fixture required');
const issuer=fixture.issuer,endpoint=input.publicOrigin+'/provider-command-peer/command',callback='https://localhost:18449/callback',cases=[];
function check(name,condition,details={}){if(!condition)throw new Error(name);cases.push({case:name,result:'pass',...details});}
const jwks=await fetch(issuer+'/jwks').then(r=>r.json()),receiver=peer({issuer,endpoint,jwks});await new Promise(resolve=>receiver.server.listen(14900,'127.0.0.1',resolve));
let returned,expectedState;
const server=createServer({cert:readFileSync(fixture.ca_file),key:readFileSync(join(dirname(fixture.ca_file),'key.pem'))},(request,response)=>{const url=new URL(request.url,callback);if(url.pathname!=='/callback'||url.searchParams.get('state')!==expectedState){response.writeHead(400);response.end();return;}returned=url;response.writeHead(200,{'content-type':'text/plain'});response.end('Owned command RP callback received');});await new Promise(resolve=>server.listen(18449,'127.0.0.1',resolve));
const browser=await chromium.launch({headless:true}),scim=new DpopClient(privateJson(input.automation));let stage='guarded setup',client,user,api,userDeleted=false;
function sql(query){const r=spawnSync('docker',['exec','-i',process.env.ASTERIUS_ACCEPTANCE_DB_CONTAINER,'psql','-U','asterius','-d',fixture.database,'-v','ON_ERROR_STOP=1','-At'],{input:query,encoding:'utf8'});if(r.status!==0)throw new Error('Owned SQL probe refused');return r.stdout.trim();}
async function waitFor(predicate){const deadline=Date.now()+30000;while(Date.now()<deadline){if(predicate())return;await new Promise(resolve=>setTimeout(resolve,250));}throw new Error('Owned delivery absent');}
try{
 const admin=await browser.newContext({ignoreHTTPSErrors:true}),page=await admin.newPage();await page.goto(issuer+'/admin/');await page.locator('input[name="username"]').fill('sweep@example.test');await page.locator('input[name="password"]').fill('correct horse battery staple');await page.getByRole('button',{name:'Sign in',exact:true}).click();await page.waitForURL(url=>url.pathname.endsWith('/admin/'));
 api=async(method,path,body)=>page.evaluate(async({method,path,body})=>{const session=await fetch('api/v1/session').then(r=>r.json());const r=await fetch('api/v1'+path,{method,headers:{'content-type':'application/json','x-csrf-token':session.csrf_token,...(method==='POST'?{'idempotency-key':crypto.randomUUID()}: {})},body:body?JSON.stringify(body):undefined});return {status:r.status,body:r.status===204?{}:await r.json().catch(()=>({non_json:true}))};},{method,path,body});
 const metadata={client_name:'Owned independent command RP',compliance_profile:'oidc',application_type:'web',token_endpoint_auth_method:'client_secret_basic',redirect_uris:[callback],grant_types:['authorization_code'],response_types:['code'],scope:'openid email',id_token_signed_response_alg:'ES256',dpop_bound_access_tokens:false,command_endpoint:endpoint};
 const unsafe=await api('POST','/clients',{...metadata,command_endpoint:'http://127.0.0.1:14900/provider-command-peer/command'});check('guarded registration refused unsafe command transport',unsafe.status===400,{observed_status:unsafe.status});
 const registered=await api('POST','/clients',metadata);check('guarded command RP registration',registered.status===201&&Boolean(registered.body.client_secret));client=registered.body;receiver.state.client=client.client_id;
 const assigned=await api('PUT','/clients/'+client.client_id+'/resources',{resources:[issuer]});check('guarded command RP audience assignment',assigned.status===200);
 const username='command-owned-'+randomBytes(5).toString('hex')+'@example.invalid',password='Owned-command-'+randomBytes(32).toString('base64url');
 const created=await api('POST','/users',{username,email:username,email_verified:false,password});check('guarded owned account creation',created.status===201&&Boolean(created.body.user_id));user=created.body.user_id;
 const context=await browser.newContext({ignoreHTTPSErrors:true}),target=await context.newPage(),verifier=randomBytes(32).toString('base64url'),nonce=randomBytes(24).toString('base64url'),url=new URL(issuer+'/authorize');expectedState=randomBytes(24).toString('base64url');
 for(const [name,value] of Object.entries({client_id:client.client_id,redirect_uri:callback,response_type:'code',scope:'openid email',state:expectedState,nonce,code_challenge:createHash('sha256').update(verifier).digest('base64url'),code_challenge_method:'S256'}))url.searchParams.set(name,value);
 await target.goto(url.toString());await target.locator('input[name="username"]').fill(username);await target.locator('input[name="password"]').fill(password);await target.getByRole('button',{name:'Sign in',exact:true}).click();const allow=target.getByRole('button',{name:'Allow',exact:true});await Promise.race([allow.waitFor({state:'visible',timeout:10000}).catch(()=>null),target.waitForURL(u=>u.port==='18449',{timeout:10000}).catch(()=>null)]);if(await allow.isVisible())await allow.click();await target.waitForURL(u=>u.port==='18449',{timeout:15000});
 const tokens=await context.request.post(issuer+'/token',{headers:{authorization:'Basic '+Buffer.from(client.client_id+':'+client.client_secret).toString('base64')},form:{grant_type:'authorization_code',code:returned.searchParams.get('code'),redirect_uri:callback,code_verifier:verifier}});check('actual independent command RP code exchange',tokens.status()===200);
 const idToken=(await tokens.json()).id_token,parts=idToken.split('.'),header=JSON.parse(Buffer.from(parts[0],'base64url')),claims=JSON.parse(Buffer.from(parts[1],'base64url')),key=jwks.keys.find(k=>k.kid===header.kid);
 check('independent RP verified real OIDC identity',header.alg==='ES256'&&claims.iss===issuer&&claims.aud===client.client_id&&claims.nonce===nonce&&verify('sha256',Buffer.from(parts.slice(0,2).join('.')),{key:createPublicKey({key,format:'jwk'}),dsaEncoding:'ieee-p1363'},Buffer.from(parts[2],'base64url')));receiver.state.subject=claims.sub;
 check('actual issued subject retained for lifecycle commands',sql("SELECT count(*) FROM provider_command_subjects WHERE tenant_id='e2e' AND client_id='"+client.client_id+"' AND user_id='"+user+"';")==='1');
 async function active(value){const current=await scim.request('GET','/Users/'+user);check('owned SCIM ETag acquired',current.status===200&&Boolean(current.headers.etag));const changed=await scim.request('PATCH','/Users/'+user,{schemas:['urn:ietf:params:scim:api:messages:2.0:PatchOp'],Operations:[{op:'replace',path:'active',value}]},{'if-match':current.headers.etag});check('actual SCIM account status transition',changed.status===200);}
 stage='malformed RP response safety';receiver.state.mode='bad_response';await active(false);await waitFor(()=>receiver.state.requests.length===1);await waitFor(()=>sql("SELECT status FROM outbox WHERE tenant_id='e2e' AND kind='provider_command.account' AND destination='"+client.client_id+"' ORDER BY outbox_id DESC LIMIT 1;")==='abandoned');
 check('producer rejects signed command response missing no-store',receiver.state.requests[0].signature_verified&&receiver.state.requests[0].status===204&&!receiver.state.requests[0].mutation&&receiver.state.sessions===1,{producer_outcome:'abandoned',observed_status:204});
 stage='real invalidate delivery';receiver.state.mode='normal';await active(true);await active(false);await waitFor(()=>receiver.state.requests.length===2);await waitFor(()=>sql("SELECT status FROM outbox WHERE tenant_id='e2e' AND kind='provider_command.account' AND destination='"+client.client_id+"' ORDER BY outbox_id DESC LIMIT 1;")==='delivered');
 check('actual signed invalidate reached public independent consumer',receiver.state.requests[1].command==='invalidate'&&receiver.state.requests[1].signature_verified&&receiver.state.sessions===0&&receiver.state.tokens===0&&receiver.state.account==='active',{observed_status:200,producer_outcome:'delivered'});
 const live=receiver.state.lastToken;
 async function probe(mode,token,expected,error){const before=JSON.stringify({account:receiver.state.account,sessions:receiver.state.sessions,tokens:receiver.state.tokens,seen:receiver.state.seen.size});receiver.state.mode=mode;const response=await fetch('http://127.0.0.1:14900/provider-command-peer/command',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({command_token:token})});const body=await response.json();check('independent consumer '+mode+' refusal',response.status===expected&&body.error===error&&before===JSON.stringify({account:receiver.state.account,sessions:receiver.state.sessions,tokens:receiver.state.tokens,seen:receiver.state.seen.size}),{observed_status:response.status,observed_error:body.error,mutation:false});receiver.state.mode='normal';}
 await probe('normal',live,400,'invalid_request');await probe('wrong_issuer',live,401,'unrecognized_provider');await probe('wrong_audience',live,400,'invalid_request');await probe('expired',live,400,'invalid_request');await probe('unsupported',live,400,'unsupported_command');const forged=live.split('.');const signature=Buffer.from(forged[2],'base64url');signature[0]^=1;forged[2]=signature.toString('base64url');await probe('forged',forged.join('.'),400,'invalid_request');
 stage='real delete delivery';const current=await scim.request('GET','/Users/'+user),deleted=await scim.request('DELETE','/Users/'+user,undefined,{'if-match':current.headers.etag});check('actual owned SCIM delete',deleted.status===204);userDeleted=true;await waitFor(()=>receiver.state.requests.length===3);await waitFor(()=>sql("SELECT status FROM outbox WHERE tenant_id='e2e' AND kind='provider_command.account' AND destination='"+client.client_id+"' ORDER BY outbox_id DESC LIMIT 1;")==='delivered');check('actual signed delete reached public independent consumer',receiver.state.requests[2].command==='delete'&&receiver.state.requests[2].signature_verified&&receiver.state.account==='unknown'&&receiver.state.sessions===0&&receiver.state.tokens===0,{observed_status:200,producer_outcome:'delivered'});
 const absent=await scim.request('GET','/Users/'+user);check('deleted owned user unavailable through SCIM',absent.status===404,{observed_status:404});sql("DELETE FROM users WHERE tenant_id='e2e' AND user_id='"+user+"' AND username LIKE 'command-owned-%@example.invalid';");
 sql("DELETE FROM clients WHERE tenant_id='e2e' AND client_id='"+client.client_id+"' AND command_endpoint='"+endpoint+"';");check('owned command RP fixture client removed',sql("SELECT count(*) FROM clients WHERE tenant_id='e2e' AND client_id='"+client.client_id+"';")==='0');client=null;
 writeFileSync(input.evidence,JSON.stringify({status:'pass',date:'2026-10-08',implementation:'independent controlled RP, native Node crypto',specification:'OpenID Provider Commands draft02,25September2025',runtime_revision:fixture.runtime_revision,asterius_binary_sha256:fixture.binary_sha256,cases,formal_conformance:false,limits:['Actual invalidate/delete are signed by Asterius and delivered over guarded public HTTPS.','Refusal probes reuse real signed tokens against pinned consumer configuration, controlled clock, unsupported policy or altered signature; they do not claim Asterius emitted wrong claims.','Only supported synchronous invalidate/delete; tenant/metadata/migrate/other draft commands and formal certification are not claimed.']},null,2),{mode:0o600});console.info(JSON.stringify({status:'pass',checks:cases.length}));
}catch(error){console.error(JSON.stringify({status:'failed',stage,type:error.name,checks:cases.length,refusals:receiver.state.refusals,reason:/^(Owned|owned|actual|guarded|independent|producer)/.test(error.message)?error.message:'browser-operation'}));process.exitCode=1;}finally{if(api&&user&&!userDeleted){try{const current=await scim.request('GET','/Users/'+user);if(current.status===200)await scim.request('DELETE','/Users/'+user,undefined,{'if-match':current.headers.etag});}catch{console.error('Owned cleanup requires retry');}}if(user)sql("DELETE FROM users WHERE tenant_id='e2e' AND user_id='"+user+"' AND username LIKE 'command-owned-%@example.invalid';");if(client)sql("DELETE FROM clients WHERE tenant_id='e2e' AND client_id='"+client.client_id+"' AND command_endpoint='"+endpoint+"';");await browser.close();await new Promise(resolve=>receiver.server.close(resolve));await new Promise(resolve=>server.close(resolve));}
