-- Initial access tokens a tenant owns, rather than strings a binary was
-- started with (`ast-cu3`).
--
-- RFC 7591 §1.2's initial access token existed here only as a set of SHA-256
-- digests read out of `asterius.toml` at boot. That made the per-tenant
-- registration policy `ast-m9c.6` stores and evaluates — `mode` and
-- `max_clients_per_initial_access_token` — a setting with no way to be
-- satisfied: a tenant narrowing an open deployment to `initial_access_token`
-- refused every caller, because there was no credential anybody could hold
-- that belonged to *that tenant*. A stored setting that cannot be satisfied is
-- worse than an absent one, which is what this table is for.
--
-- One row per issued token. The plaintext exists for exactly one HTTP response
-- — the admin API call that created it — and is never stored, in line with
-- registration access tokens (`clients.registration_access_token`) and refresh
-- tokens: a bare SHA-256 is the right at-rest form for a value with this much
-- entropy (`asterius_domain::credentials`), and it means a database dump
-- carries nothing that can be replayed at `POST /register`.
--
-- A migration of its own rather than an edit to the baseline, for the reason
-- 0002 gives: editing a baseline changes a checksum sqlx refuses to run
-- against a database that already applied it.

create table initial_access_tokens (
    -- Generated by the adapter, as every other identifier in this schema is:
    -- no row here has a database-side default, and adding the first one would
    -- make the id depend on which side wrote the row.
    id           uuid        not null,
    tenant_id    text        not null
                 references tenants (tenant_id) on delete cascade,
    -- What an operator called it, shown in the console and written to the
    -- audit trail. Not a credential; bounded here rather than in the adapter,
    -- because a constraint is what makes it true of every writer.
    label        text        not null check (length(label) <= 200),
    -- SHA-256 of the token. Never the token.
    --
    -- Unique across the deployment and not merely within the tenant: two
    -- tenants holding the same digest would mean one string admitted at two
    -- issuers, and the lookup below is by `(tenant_id, token_hash)` so the
    -- collision would be silent rather than an error somebody sees.
    token_hash   bytea       not null check (octet_length(token_hash) = 32),
    -- Clients created with this token so far, and its ceiling.
    --
    -- `max_uses` is stamped at issuance from the tenant's
    -- `max_clients_per_initial_access_token`, not read from the policy
    -- document when the token is spent: a policy edit must not silently
    -- re-open credentials an operator has already spent, and "how many clients
    -- can this token still create" has to be answerable from the row.
    --
    -- `null` is "no ceiling", which is what a tenant that sets no quota gets.
    -- Zero is refused: a token that may register nothing is not worth issuing,
    -- and a caller holding one would be told `invalid_token` forever.
    uses         integer     not null default 0 check (uses >= 0),
    max_uses     integer     check (max_uses > 0),
    -- When it stops being accepted, or `null` for "until it is deleted".
    expires_at   timestamptz,
    created_at   timestamptz not null default now(),
    -- Who issued it. The console becomes an issuer of credentials that create
    -- clients, so the actor is on the row as well as in the audit trail: the
    -- trail answers "what happened", this answers "who is this token's" while
    -- the token is still live.
    created_by   text        not null,

    primary key (tenant_id, id),
    unique (token_hash)
);

-- The admission lookup: one tenant's token by digest. Covered by the unique
-- index on `token_hash` alone, but the statement filters on `tenant_id` too —
-- a token of tenant A presented at tenant B must miss, not merely be refused
-- afterwards — and this keeps that filter index-backed.
create index initial_access_tokens_tenant_hash
    on initial_access_tokens (tenant_id, token_hash);

comment on table initial_access_tokens is
    'RFC 7591 initial access tokens issued to one tenant by the admin API. '
    'Stored as SHA-256 digests; the plaintext exists for one response only. '
    'uses/max_uses is the per-token client quota from the tenant registration '
    'policy, charged atomically at POST /register.';
