import assert from 'node:assert/strict';
import {createServer} from 'node:https';
import {readFile,writeFile,chmod} from 'node:fs/promises';
import {execFileSync} from 'node:child_process';
import {createHash,randomBytes,randomUUID} from 'node:crypto';
import {chromium} from '../../e2e/node_modules/playwright-core/index.mjs';
import {decodeProtectedHeader,importJWK,jwtVerify} from '../../e2e/node_modules/jose/dist/webapi/index.js';
const input=JSON.parse(await readFile(process.argv[2],'utf8'));
assert(input.database.startsWith('ast_product_'));
const actor='3f1d5c2a-0000-4000-8000-000000000001';
const subject='3f1d5c2a-0000-4000-8000-000000000099';
const callbackUrl='https://localhost:9479/callback';
const checks=[];let stage='bootstrap',callback;
const quote=v=>"'"+v.replaceAll("'","''")+"'";
function sql(body){return execFileSync('docker',['exec','-i',input.db_container,'psql','-U','asterius','-d',input.database,'-X','-At','-v','ON_ERROR_STOP=1'],{input:body,encoding:'utf8',stdio:['pipe','pipe','pipe']}).trim();}
const callbackServer=createServer({key:await readFile(input.tls_key),cert:await readFile(input.tls_certificate)},(request,response)=>{callback=new URL(request.url,callbackUrl);response.writeHead(200,{'Content-Type':'text/html'});response.end('<!doctype html><title>Controlled callback</title><p>Callback received</p>');});
await new Promise((resolve,reject)=>{callbackServer.once('error',reject);callbackServer.listen(9479,'127.0.0.1',resolve);});
const browser=await chromium.launch({headless:true,args:['--no-sandbox','--host-resolver-rules=MAP localhost 127.0.0.1']});
try{
 const context=await browser.newContext({ignoreHTTPSErrors:true});
 const page=await context.newPage();page.setDefaultTimeout(15000);
 const cdp=await context.newCDPSession(page);await cdp.send('WebAuthn.enable');
 const {authenticatorId}=await cdp.send('WebAuthn.addVirtualAuthenticator',{options:{protocol:'ctap2',transport:'internal',hasResidentKey:true,hasUserVerification:true,isUserVerified:true,automaticPresenceSimulation:true}});
 function flow(extra={}){callback=undefined;const verifier=randomBytes(32).toString('base64url');const state=randomBytes(24).toString('base64url');const params=new URLSearchParams({response_type:'code',client_id:input.client_id,redirect_uri:callbackUrl,scope:'openid email',state,nonce:randomBytes(24).toString('base64url'),code_challenge_method:'S256',code_challenge:createHash('sha256').update(verifier).digest('base64url'),...extra});return {url:input.issuer+'/authorize?'+params,verifier,state};}
 async function complete(){const allow=page.getByRole('button',{name:'Allow',exact:true});await Promise.race([allow.waitFor({state:'visible'}),page.waitForURL(u=>u.port==='9479')]);if(await allow.isVisible())await allow.click();await page.waitForURL(u=>u.port==='9479');}
 assert.equal(sql(`select count(*) from user_roles where tenant_id='e2e' and user_id='${actor}' and role='tenant_admin';`),'1');
 stage='password baseline';const initial=flow();await page.goto(initial.url);await page.locator('input[name="username"]').fill('sweep@example.test');await page.locator('input[name="password"]').fill('correct horse battery staple');await page.getByRole('button',{name:'Sign in',exact:true}).click();await complete();assert(callback.searchParams.has('code'));assert.equal(callback.searchParams.get('state'),initial.state);
 const api=input.issuer+'/admin/api/v1/';
 async function session(){const r=await context.request.get(api+'session');assert.equal(r.status(),200);return r.json();}
 let identity=await session();assert.equal(identity.tenant,'e2e');
 async function request(method,path,data,options={}){const headers={Origin:new URL(input.issuer).origin,'Content-Type':'application/json','X-CSRF-Token':identity.csrf_token,...options.headers};if(method==='POST')headers['Idempotency-Key']=randomUUID();if(options.noCsrf)delete headers['X-CSRF-Token'];return context.request.fetch(api+path,{method,headers,...(data===undefined?{}:{data})});}
 const seedTarget={kind:'user_tenant_role',user_id:subject,name:'review-reader'};
 const configure=target=>({target,owner_user_id:actor,reviewers:[actor],enabled:true,expected_revision:null});
 sql("insert into tenant_roles(tenant_id,name) values('e2e','review-reader');insert into user_tenant_roles(tenant_id,user_id,name) values('e2e','"+subject+"','review-reader');");
 const weak=await request('PUT','governance/ownership',configure(seedTarget));assert([403,409].includes(weak.status()));checks.push('password_session_cannot_configure_governance');
 stage='real user verified passkey';await page.goto(input.issuer+'/passkeys');await page.getByRole('button',{name:'Create a passkey',exact:true}).click();await page.waitForFunction(()=>location.pathname.endsWith('/account')||document.querySelector('#passkey-status')?.textContent?.includes('created'),{},{timeout:15000});const {credentials}=await cdp.send('WebAuthn.getCredentials',{authenticatorId});assert.equal(credentials.length,1);assert.equal(credentials[0].rpId,'localhost');
 const policy={version:1,rules:[],conditional_scopes:[{id:'governance-human',mode:'active',clients:[input.client_id],actions:['authorize','authorization_code'],assurance_remedy:'phr',rules:[{id:'fresh-human',effect:'permit',subject_type:'user',when:{all:[{acr_at_least:'phr'},{authentication_age_at_most:120}]}}]}]};
 sql(`insert into tenant_policies(tenant_id,document,updated_at) values('e2e',${quote(JSON.stringify(policy))}::jsonb,now()) on conflict(tenant_id) do update set document=excluded.document,updated_at=excluded.updated_at;`);
 stage='fresh actual assertion';const strong=flow({max_age:'0'});await page.goto(strong.url);await complete();assert(callback.searchParams.has('code'));assert.equal(callback.searchParams.get('state'),strong.state);
 const exchange=await context.request.post(input.issuer+'/token',{headers:{Authorization:'Basic '+Buffer.from(input.client_id+':'+input.secret).toString('base64'),'Content-Type':'application/x-www-form-urlencoded'},data:new URLSearchParams({grant_type:'authorization_code',code:callback.searchParams.get('code'),redirect_uri:callbackUrl,code_verifier:strong.verifier}).toString()});assert.equal(exchange.status(),200);const tokens=await exchange.json();const jwks=await (await context.request.get(input.issuer+'/jwks')).json();const header=decodeProtectedHeader(tokens.id_token);const key=await importJWK(jwks.keys.find(k=>k.kid===header.kid),header.alg);const {payload}=await jwtVerify(tokens.id_token,key,{issuer:input.issuer,audience:input.client_id});assert(payload.amr.includes('pop'));assert(['phr','urn:asterius:acr:passkey','urn:asterius:acr:passkey-uv'].includes(payload.acr));assert(Date.now()/1000-payload.auth_time<120);
 await writeFile(input.cookie_file,JSON.stringify(await context.cookies()),{mode:0o600});await chmod(input.cookie_file,0o600);identity=await session();checks.push('real_fresh_user_verified_webauthn_and_signed_assurance');
 async function jsonOk(r){assert.equal(r.status(),200);return r.json();}
 stage='authority boundary refusals';assert.equal((await request('PUT','governance/ownership',configure(seedTarget),{noCsrf:true})).status(),403);checks.push('csrf_required');assert.equal((await request('PUT','governance/ownership',{...configure(seedTarget),actor})).status(),400);checks.push('posted_actor_rejected');
 async function review(target,decision='remove'){const owner=await jsonOk(await request('PUT','governance/ownership',configure(target)));const review=await jsonOk(await request('POST','governance/reviews',{ownership_ids:[owner.id],reviewer_id:actor,due_at:new Date(Date.now()+3600000).toISOString()}));const items=await jsonOk(await request('GET',`governance/reviews/${review.id}/items`));assert.equal(items.items.length,1);const item=items.items[0];const base=`governance/reviews/${review.id}/items/${item.id}`;await jsonOk(await request('PUT',base+'/decision',{decision,reason:'Controlled governance verification'}));return {owner,review,item,base};}
 stage='retain without revocation';let selected=await review(seedTarget,'retain');assert.equal((await jsonOk(await request('POST',selected.base+'/apply',{}))).apply_status,'retained');checks.push('retain_preserves_assignment');
 const second=await jsonOk(await request('PUT','governance/ownership',{...configure(seedTarget),expected_revision:selected.owner.revision}));assert.notEqual(second.revision,selected.owner.revision);
 // Further scenarios use new exact sources, so ownership CAS never fabricates a revision.
 let index=0;
 function fresh(kind){const name='review-role-'+(++index);const group=randomUUID();sql(`insert into tenant_roles(tenant_id,name) values('e2e','${name}');insert into client_roles(tenant_id,client_id,name) values('e2e',${quote(input.client_id)},'${name}');insert into managed_groups(tenant_id,group_id,name,display_name,created_at,updated_at) values('e2e','${group}','review-group-${index}','Review group',now(),now());`);let target,table,where;
 if(kind==='membership'){sql(`insert into group_memberships(tenant_id,group_id,user_id,created_at) values('e2e','${group}','${subject}',now());`);target={kind,group_id:group,user_id:subject};table='group_memberships';where=`group_id='${group}' and user_id='${subject}'`;}
 else if(kind==='user_tenant_role'){sql(`insert into user_tenant_roles(tenant_id,user_id,name) values('e2e','${subject}','${name}');`);target={kind,user_id:subject,name};table='user_tenant_roles';where=`user_id='${subject}' and name='${name}'`;}
 else if(kind==='user_client_role'){sql(`insert into user_client_roles(tenant_id,user_id,client_id,name) values('e2e','${subject}',${quote(input.client_id)},'${name}');`);target={kind,user_id:subject,client_id:input.client_id,name};table='user_client_roles';where=`user_id='${subject}' and client_id=${quote(input.client_id)} and name='${name}'`;}
 else {sql(`insert into group_memberships(tenant_id,group_id,user_id,created_at) values('e2e','${group}','${subject}',now());`);table=kind==='group_tenant_role'?'group_tenant_roles':'group_client_roles';const client=kind==='group_client_role';sql(`insert into ${table}(tenant_id,group_id,${client?'client_id,':''}name) values('e2e','${group}',${client?quote(input.client_id)+',':''}'${name}');`);target={kind,group_id:group,name,...(client?{client_id:input.client_id}:{})};where=`group_id='${group}' and name='${name}'`;}
 return {target,table,where,group,name};}
 for(const kind of ['membership','user_tenant_role','user_client_role','group_tenant_role','group_client_role']){stage='remove '+kind;const source=fresh(kind);let independentGroup;
 if(kind==='membership'){independentGroup=randomUUID();sql(`insert into managed_groups(tenant_id,group_id,name,display_name,created_at,updated_at) values('e2e','${independentGroup}','independent-baseline','Independent baseline',now(),now());insert into group_memberships(tenant_id,group_id,user_id,created_at) values('e2e','${independentGroup}','${subject}',now());insert into group_tenant_roles(tenant_id,group_id,name) values('e2e','${source.group}','${source.name}'),('e2e','${independentGroup}','${source.name}');insert into user_tenant_roles(tenant_id,user_id,name) values('e2e','${subject}','${source.name}');`);}
 selected=await review(source.target);const result=await jsonOk(await request('POST',selected.base+'/apply',{}));assert.equal(result.apply_status,'removed');assert.equal(sql(`select count(*) from ${source.table} where tenant_id='e2e' and ${source.where};`),'0');checks.push(kind+'_existing_lifecycle_removal');
 if(kind==='membership'){assert.equal(sql(`select count(*) from user_tenant_roles where tenant_id='e2e' and user_id='${subject}' and name='${source.name}';`),'1');assert.equal(sql(`select count(*) from group_memberships where tenant_id='e2e' and group_id='${independentGroup}' and user_id='${subject}';`),'1');checks.push('membership_removal_preserves_direct_and_independent_group_sources');}}
 stage='new group member';const changed=fresh('group_tenant_role');selected=await review(changed.target);sql(`insert into group_memberships(tenant_id,group_id,user_id,created_at) values('e2e','${changed.group}','${actor}',now());`);assert.equal((await jsonOk(await request('POST',selected.base+'/apply',{}))).apply_status,'conflict');checks.push('new_group_member_invalidates_group_role_snapshot');
 stage='ownership revision';const revised=fresh('user_tenant_role');selected=await review(revised.target);await jsonOk(await request('PUT','governance/ownership',{...configure(revised.target),expected_revision:selected.owner.revision}));assert.equal((await jsonOk(await request('POST',selected.base+'/apply',{}))).apply_status,'conflict');checks.push('ownership_change_invalidates_pending_application');
 stage='generation drift';const source=fresh('user_tenant_role');selected=await review(source.target);sql(`delete from user_tenant_roles where tenant_id='e2e' and ${source.where};insert into user_tenant_roles(tenant_id,user_id,name) values('e2e','${subject}','${source.name}');`);assert.equal((await jsonOk(await request('POST',selected.base+'/apply',{}))).apply_status,'conflict');checks.push('recreated_assignment_is_not_revoked');
 stage='controller protection';const managed=fresh('membership');sql(`update declarative_owners set owner='urn:test:controller',deletion_protection=false where tenant_id='e2e' and kind='group' and keys=jsonb_build_array('${managed.group}'::text);`);selected=await review(managed.target);assert.equal((await jsonOk(await request('POST',selected.base+'/apply',{}))).apply_status,'protected');checks.push('controller_authority_is_not_impersonated');
 stage='concurrent durable application';const concurrent=fresh('user_tenant_role');selected=await review(concurrent.target);const results=await Promise.all([request('POST',selected.base+'/apply',{}),request('POST',selected.base+'/apply',{})]);for(const r of results)assert.equal((await jsonOk(r)).apply_status,'removed');assert.equal(sql(`select count(*) from audit_events where tenant_id='e2e' and detail->>'operation'='governance.review.apply' and subject='${selected.item.id}';`),'1');checks.push('two_requests_one_durable_application');
 stage='audit rollback';const rollback=fresh('user_tenant_role');selected=await review(rollback.target);sql("create function controlled_governance_audit_refusal() returns trigger language plpgsql as $$begin raise exception 'controlled refusal';end$$;create trigger controlled_governance_audit_refusal before insert on audit_events for each row execute function controlled_governance_audit_refusal();");try{assert.equal((await request('POST',selected.base+'/apply',{})).status(),503);}finally{sql('drop trigger controlled_governance_audit_refusal on audit_events;drop function controlled_governance_audit_refusal();');}assert.equal(sql(`select count(*) from user_tenant_roles where tenant_id='e2e' and ${rollback.where};`),'1');const pending=await jsonOk(await request('GET',`governance/reviews/${selected.review.id}/items`));assert.equal(pending.items[0].apply_status,'pending');checks.push('failed_audit_rolls_back_removal_and_result');
 stage='live reviewer revoked';sql(`delete from user_roles where tenant_id='e2e' and user_id='${actor}' and role='tenant_admin';`);assert([403,409].includes((await request('POST',selected.base+'/apply',{})).status()));checks.push('live_reviewer_authority_rechecked');
 console.log(JSON.stringify({checks,passed:checks.length,real_webauthn:true,private_cookie_file:true,owned_database_only:true}));await context.close();
}catch{console.error('ACCESS_REVIEW_STAGE='+stage);process.exitCode=1;}
finally{await browser.close();await new Promise(resolve=>callbackServer.close(resolve));}
