apiVersion: v1
kind: Service
metadata:
  name: {{ include "asterius.fullname" . }}
  labels:
    {{- include "asterius.labels" . | nindent 4 }}
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{ .Values.service.portName }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.portName }}
      protocol: TCP
  selector:
    {{- include "asterius.selectorLabels" . | nindent 4 }}
