import assert from 'node:assert/strict';
import {targetClient} from './target_controls.mjs';
import {createServer} from 'node:https';
import {readFile,writeFile,chmod,rename} from 'node:fs/promises';
import {execFileSync} from 'node:child_process';
import {createHash,randomBytes,randomUUID} from 'node:crypto';
import {chromium} from '../../e2e/node_modules/playwright-core/index.mjs';
import {decodeProtectedHeader,importJWK,jwtVerify} from '../../e2e/node_modules/jose/dist/webapi/index.js';
const input=JSON.parse(await readFile(process.argv[2],'utf8'));
assert(input.database.startsWith('ast_outbound_source_'));assert(input.target_database.startsWith('ast_outbound_target_'));
const actor='3f1d5c2a-0000-4000-8000-000000000001';
const subject='3f1d5c2a-0000-4000-8000-000000000099';
const callbackUrl='https://localhost:9479/callback';
const checks=[];let stage='bootstrap',callback,lastStatus,lastFailure;
const quote=v=>"'"+v.replaceAll("'","''")+"'";
function sql(body){try{return execFileSync('docker',['exec','-i',input.db_container,'psql','-U','asterius','-d',input.database,'-X','-At','-v','ON_ERROR_STOP=1','-v','VERBOSITY=verbose'],{input:body,encoding:'utf8',stdio:['pipe','pipe','pipe']}).trim();}catch(error){const text=String(error.stderr??'');const state=text.match(/ERROR:\s+([0-9A-Z]{5}):/)?.[1]??'unknown';const constraint=text.match(/CONSTRAINT NAME:\s+([a-zA-Z0-9_]+)/)?.[1]??'none';const fn=text.match(/PL\/pgSQL function ([a-zA-Z0-9_]+)/)?.[1]??'none';throw Error('OWN_SQL_ERROR='+state+' CONSTRAINT='+constraint+' FUNCTION='+fn);}}
const callbackServer=createServer({key:await readFile(input.tls_key),cert:await readFile(input.tls_certificate)},(request,response)=>{callback=new URL(request.url,callbackUrl);response.writeHead(200,{'Content-Type':'text/html'});response.end('<!doctype html><title>Controlled callback</title><p>Callback received</p>');});
await new Promise((resolve,reject)=>{callbackServer.once('error',reject);callbackServer.listen(9479,'127.0.0.1',resolve);});
const browser=await chromium.launch({headless:true,args:['--no-sandbox','--host-resolver-rules=MAP localhost 127.0.0.1']});
try{
 const context=await browser.newContext({ignoreHTTPSErrors:true});
 const page=await context.newPage();page.setDefaultTimeout(15000);
 const cdp=await context.newCDPSession(page);await cdp.send('WebAuthn.enable');
 const {authenticatorId}=await cdp.send('WebAuthn.addVirtualAuthenticator',{options:{protocol:'ctap2',transport:'internal',hasResidentKey:true,hasUserVerification:true,isUserVerified:true,automaticPresenceSimulation:true}});
 function flow(extra={}){callback=undefined;const verifier=randomBytes(32).toString('base64url');const state=randomBytes(24).toString('base64url');const params=new URLSearchParams({response_type:'code',client_id:input.client_id,redirect_uri:callbackUrl,scope:'openid email',state,nonce:randomBytes(24).toString('base64url'),code_challenge_method:'S256',code_challenge:createHash('sha256').update(verifier).digest('base64url'),...extra});return {url:input.issuer+'/authorize?'+params,verifier,state};}
 async function complete(){const allow=page.getByRole('button',{name:'Allow',exact:true});await Promise.race([allow.waitFor({state:'visible'}),page.waitForURL(u=>u.port==='9479')]);if(await allow.isVisible())await allow.click();await page.waitForURL(u=>u.port==='9479');}
 assert.equal(sql(`select count(*) from user_roles where tenant_id='e2e' and user_id='${actor}' and role='tenant_admin';`),'1');
 stage='password baseline';const initial=flow();await page.goto(initial.url);await page.locator('input[name="username"]').fill('sweep@example.test');await page.locator('input[name="password"]').fill('correct horse battery staple');await page.getByRole('button',{name:'Sign in',exact:true}).click();await complete();assert(callback.searchParams.has('code'));assert.equal(callback.searchParams.get('state'),initial.state);
 const api=input.issuer+'/admin/api/v1/';
 async function session(){const r=await context.request.get(api+'session');assert.equal(r.status(),200);return r.json();}
 let identity=await session();assert.equal(identity.tenant,'e2e');
 async function request(method,path,data,options={}){const headers={Origin:new URL(input.issuer).origin,'Content-Type':'application/json','X-CSRF-Token':identity.csrf_token,...options.headers};if(method==='POST')headers['Idempotency-Key']=randomUUID();if(options.noCsrf)delete headers['X-CSRF-Token'];return context.request.fetch(api+path,{method,headers,...(data===undefined?{}:{data})});}
 const configure=(current,overrides={})=>({expected_revision:current?.revision??null,target_issuer:input.target_issuer,target_client:'outbound-peer',credential_ref:'owned-peer',credential_generation:current?.credential_generation??input.credential_generation,enabled:false,allow_reviewed_delete:false,...overrides});
 stage='weak human refusal';assert.equal((await request('POST','outbound-scim/connectors',configure())).status(),401);checks.push('password_session_cannot_configure_outbound');
 stage='real user verified passkey';await page.goto(input.issuer+'/passkeys');await page.getByRole('button',{name:'Create a passkey',exact:true}).click();await page.waitForFunction(()=>location.pathname.endsWith('/account')||document.querySelector('#passkey-status')?.textContent?.toLowerCase().includes('created'),{},{timeout:15000}).catch(()=>null);const {credentials}=await cdp.send('WebAuthn.getCredentials',{authenticatorId});assert.equal(credentials.length,1);assert.equal(credentials[0].rpId,'localhost');
 const policy={version:1,rules:[],conditional_scopes:[{id:'outbound-human',mode:'active',clients:[input.client_id],actions:['authorize','authorization_code'],assurance_remedy:'phr',rules:[{id:'fresh-human',effect:'permit',subject_type:'user',when:{all:[{acr_at_least:'phr'},{authentication_age_at_most:120}]}}]}]};
 sql(`insert into tenant_policies(tenant_id,document,updated_at) values('e2e',${quote(JSON.stringify(policy))}::jsonb,now()) on conflict(tenant_id) do update set document=excluded.document,updated_at=excluded.updated_at;`);
 stage='fresh actual assertion';const strong=flow({max_age:'0'});await page.goto(strong.url);await complete();assert(callback.searchParams.has('code'));assert.equal(callback.searchParams.get('state'),strong.state);
 const exchange=await context.request.post(input.issuer+'/token',{headers:{Authorization:'Basic '+Buffer.from(input.client_id+':'+input.secret).toString('base64'),'Content-Type':'application/x-www-form-urlencoded'},data:new URLSearchParams({grant_type:'authorization_code',code:callback.searchParams.get('code'),redirect_uri:callbackUrl,code_verifier:strong.verifier}).toString()});assert.equal(exchange.status(),200);const tokens=await exchange.json();const jwks=await (await context.request.get(input.issuer+'/jwks')).json();const header=decodeProtectedHeader(tokens.id_token);const key=await importJWK(jwks.keys.find(k=>k.kid===header.kid),header.alg);const {payload}=await jwtVerify(tokens.id_token,key,{issuer:input.issuer,audience:input.client_id});assert(payload.amr.includes('pop'));assert(['phr','urn:asterius:acr:passkey','urn:asterius:acr:passkey-uv'].includes(payload.acr));assert(Date.now()/1000-payload.auth_time<120);
 await writeFile(input.cookie_file,JSON.stringify(await context.cookies()),{mode:0o600});await chmod(input.cookie_file,0o600);identity=await session();checks.push('real_fresh_user_verified_webauthn_and_signed_assurance');
 async function jsonOk(r){lastStatus=r.status();const value=await r.json();if(lastStatus!==200){const diagnostic=JSON.stringify(value);lastFailure=['paused','credential_unavailable','credential_binding_mismatch','authentication_refused','target_unavailable','ownership_mismatch','target_absent','target_version_changed','source_protected','source_projection_invalid','user_dependencies_pending','snapshot_bound_exceeded','lease_superseded'].find(code=>diagnostic.includes(code));}assert.equal(lastStatus,200);return value;}
 async function injectFault(value){const staged=input.fault_file+'.'+randomUUID();await writeFile(staged,JSON.stringify(value),{mode:0o600});await rename(staged,input.fault_file);}
 const targetSql=body=>execFileSync('docker',['exec','-i',input.db_container,'psql','-U','asterius','-d',input.target_database,'-X','-At','-v','ON_ERROR_STOP=1'],{input:body,encoding:'utf8',stdio:['pipe','pipe','pipe']}).trim();
 const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));
 async function until(probe){const deadline=Date.now()+25000;while(Date.now()<deadline){const value=await probe();if(value)return value;sql("update outbox set available_at=now() where tenant_id='e2e' and kind like 'outbound_scim.%' and status in ('pending','failed');");await wait(200);}throw Error('bounded fixture state deadline');}
 const descriptors=await jsonOk(await request('GET','outbound-scim/credentials'));assert.equal(descriptors.items.length,2);assert.equal(descriptors.items[0].reference,'owned-peer');assert(!JSON.stringify(descriptors).includes('operator.der'));checks.push('scoped_operator_descriptor_has_no_private_path');
 stage='closed metadata refusal';assert.equal((await request('POST','outbound-scim/connectors',{...configure(),actor})).status(),400);assert.equal((await request('POST','outbound-scim/connectors',configure(null,{enabled:true}))).status(),400);checks.push('posted_actor_and_enabled_create_refused');assert.equal((await request('POST','outbound-scim/connectors',configure(null,{target_issuer:'https://127.0.0.1:9446/t/target'}))).status(),400);assert.equal((await request('POST','outbound-scim/connectors',configure(null,{target_client:'different-principal'}))).status(),409);checks.push('private_target_and_credential_context_mismatch_refused');
 let connector=await jsonOk(await request('POST','outbound-scim/connectors',configure()));const base='outbound-scim/connectors/'+connector.id;
 stage='fresh preview';const preview=await jsonOk(await request('POST',base+'/preview',{expected_revision:connector.revision}));assert.equal(preview.etag_supported,true);assert.equal(preview.filter_supported,true);checks.push('actual_guarded_tls_private_key_jwt_dpop_and_capability_preview');
 stage='paused selection';let assignment=(await jsonOk(await request('POST',base+'/assignments',{expected_revision:connector.revision,kind:'user',sources:[subject]}))).items[0];assert.equal(assignment.target,null);
 assert.equal((await request('PUT',base,configure(connector,{enabled:true,allow_reviewed_delete:true}))).status(),409);checks.push('selection_revision_invalidates_prior_activation_preview');connector=await jsonOk(await request('GET',base));await jsonOk(await request('POST',base+'/preview',{expected_revision:connector.revision}));
 await injectFault({method:'POST',path:'/t/target/admin/api/v1/scim/v2/Users',action:'drop_after_commit'});
 connector=await jsonOk(await request('PUT',base,configure(connector,{enabled:true,allow_reviewed_delete:true})));
 async function assignments(){return (await jsonOk(await request('GET',base+'/assignments?limit=100'))).items;}
 async function settled(id){return until(async()=>{const row=(await assignments()).find(a=>a.id===id);return row?.target&&!row.dirty?row:undefined;});}
 stage='lost create recovery';assignment=await settled(assignment.id);assert.equal(targetSql("select count(*) from scim_user_external_ids where tenant_id='target' and client_id='outbound-peer';"),'1');checks.push('committed_post_lost_response_recovers_exactly_one_target_uuid');assert.equal(targetSql(`select count(*) from credentials where tenant_id='target' and user_id='${assignment.target}';`),'0');assert.equal(targetSql(`select (select count(*) from user_tenant_roles where tenant_id='target' and user_id='${assignment.target}')+(select count(*) from user_client_roles where tenant_id='target' and user_id='${assignment.target}');`),'0');checks.push('remote_account_contains_no_authenticators_or_privileged_role_assignments');
 stage='dry run';const before=await readFile(input.relay_evidence,'utf8');const inspection=await jsonOk(await request('POST',base+'/assignments/'+assignment.id+'/dry-run',{expected_revision:connector.revision}));assert.equal(inspection.target,assignment.target);const calls=(await readFile(input.relay_evidence,'utf8')).slice(before.length).trim().split('\n').filter(Boolean).map(JSON.parse);assert(calls.filter(c=>c.family!=='token').every(c=>c.method==='GET'));checks.push('dry_run_scim_get_only_and_mapping_unchanged');
 stage='bounded target outage';await injectFault({method:'GET',path:'/t/target/admin/api/v1/scim/v2/Users/'+assignment.target,action:'refuse'});sql(`update users set email='outage-outbound@example.test' where tenant_id='e2e' and user_id='${subject}';`);assignment=await settled(assignment.id);assert.equal(targetSql(`select email from users where tenant_id='target' and user_id='${assignment.target}';`),'outage-outbound@example.test');checks.push('real_peer_503_durable_retry_then_current_projection_recovery');
 stage='current source email';sql(`update users set email='changed-outbound@example.test' where tenant_id='e2e' and user_id='${subject}';`);assignment=await settled(assignment.id);assert.equal(targetSql(`select email from users where tenant_id='target' and user_id='${assignment.target}';`),'changed-outbound@example.test');checks.push('producer_reads_current_source_email');
 stage='direct selected group';await injectFault({method:'POST',path:'/t/target/admin/api/v1/scim/v2/Groups',action:'drop_after_commit'});const group=randomUUID();sql(`insert into managed_groups(tenant_id,group_id,name,display_name,created_at,updated_at) values('e2e','${group}','owned-outbound-group','Owned outbound group',now(),now());insert into group_memberships(tenant_id,group_id,user_id,created_at) values('e2e','${group}','${subject}',now());`);let groupAssignment=(await jsonOk(await request('POST',base+'/assignments',{expected_revision:connector.revision,kind:'group',sources:[group]}))).items[0];groupAssignment=await settled(groupAssignment.id);connector=await jsonOk(await request('GET',base));assert.equal(targetSql(`select count(*) from group_memberships where tenant_id='target' and group_id='${groupAssignment.target}' and user_id='${assignment.target}';`),'1');checks.push('complete_direct_selected_user_group_projection');assert.equal(targetSql("select count(*) from scim_group_owners where tenant_id='target' and client_id='outbound-peer';"),'1');checks.push('committed_group_post_lost_response_recovers_one_target_uuid');
 stage='source disable';sql(`update users set status='disabled' where tenant_id='e2e' and user_id='${subject}';`);assignment=await settled(assignment.id);assert.equal(targetSql(`select status from users where tenant_id='target' and user_id='${assignment.target}';`),'disabled');groupAssignment=await settled(groupAssignment.id);assert.equal(targetSql(`select count(*) from group_memberships where tenant_id='target' and group_id='${groupAssignment.target}';`),'0');checks.push('source_disable_preserves_uuid_and_empties_ineligible_group_member');
 stage='target lock';targetSql(`update users set status='locked' where tenant_id='target' and user_id='${assignment.target}';`);sql(`update users set status='active' where tenant_id='e2e' and user_id='${subject}';`);await until(async()=>{const row=(await assignments()).find(a=>a.id===assignment.id);return row?.failure_code?row:undefined;});assert.equal(targetSql(`select status from users where tenant_id='target' and user_id='${assignment.target}';`),'locked');checks.push('source_reactivation_cannot_clear_target_security_lock');targetSql(`update users set status='disabled' where tenant_id='target' and user_id='${assignment.target}';`);await jsonOk(await request('POST',base+'/reconcile',{expected_revision:connector.revision}));assignment=await settled(assignment.id);checks.push('operator_resolved_permanent_conflict_requires_explicit_reconciliation');
 stage='pause';connector=await jsonOk(await request('PUT',base,configure(connector,{enabled:false,allow_reviewed_delete:true})));sql(`update users set email='paused-outbound@example.test' where tenant_id='e2e' and user_id='${subject}';`);await until(async()=>((await assignments()).find(a=>a.id===assignment.id)?.state==='paused'));assert.equal(targetSql(`select email from users where tenant_id='target' and user_id='${assignment.target}';`),'changed-outbound@example.test');checks.push('paused_connector_keeps_dirty_and_refuses_delivery');
 stage='fresh preview after pause';await jsonOk(await request('POST',base+'/preview',{expected_revision:connector.revision}));connector=await jsonOk(await request('PUT',base,configure(connector,{enabled:true,allow_reviewed_delete:true})));assignment=await settled(assignment.id);assert.equal(targetSql(`select email from users where tenant_id='target' and user_id='${assignment.target}';`),'paused-outbound@example.test');checks.push('resumed_catalogue_reconciles_current_projection');
 stage='credential rotation';connector=await jsonOk(await request('PUT',base,configure(connector,{enabled:false,allow_reviewed_delete:true})));connector=await jsonOk(await request('PUT',base,configure(connector,{credential_generation:input.next_credential_generation,enabled:false,allow_reviewed_delete:true})));const unavailable=await request('POST',base+'/preview',{expected_revision:connector.revision});assert([409,503].includes(unavailable.status()));targetSql(`update clients set jwks=jsonb_build_object('keys',jwks->'keys' || ${quote(JSON.stringify([input.next_public_jwk]))}::jsonb) where tenant_id='target' and client_id='outbound-peer';`);await jsonOk(await request('POST',base+'/preview',{expected_revision:connector.revision}));connector=await jsonOk(await request('PUT',base,configure(connector,{enabled:true,allow_reviewed_delete:true})));assignment=await settled(assignment.id);assert.equal(connector.credential_generation,input.next_credential_generation);checks.push('uninstalled_target_key_refused_then_scoped_rotation_and_fresh_preview_recover');
 stage='unselection';await jsonOk(await request('POST',base+'/assignments/'+assignment.id+'/unselect',{expected_revision:connector.revision}));assignment=await settled(assignment.id);groupAssignment=await settled(groupAssignment.id);connector=await jsonOk(await request('GET',base));
 stage='fresh ceremony for lifecycle';const renewed=flow({max_age:'0'});await page.goto(renewed.url);await complete();assert(callback.searchParams.has('code'));identity=await session();
 async function lifecycle(row,kind){return jsonOk(await request('POST',base+'/assignments/'+row.id+'/lifecycle',{expected_revision:connector.revision,expected_generation:row.generation,kind,target:row.target,etag:row.observed_etag,confirmed:true}));}
 await injectFault({method:'DELETE',path:'/t/target/admin/api/v1/scim/v2/Users/'+assignment.target,action:'drop_after_commit'});
 stage='reviewed delete lost receipt';const deletion=await lifecycle(assignment,'delete');await until(async()=>{const rows=(await jsonOk(await request('GET',base+'/assignments/'+assignment.id+'/lifecycle'))).items;return rows.find(r=>r.id===deletion.id)?.completed;});assert.equal(targetSql(`select count(*) from scim_user_external_ids where tenant_id='target' and user_id='${assignment.target}' and deleted_at is not null;`),'1');checks.push('reviewed_delete_commit_lost_response_recovers_saved_uuid_absence');
 stage='reserved deletion privacy and late incarnation';assert.equal(targetSql(`select (email is null and not email_verified)::text from users where tenant_id='target' and user_id='${assignment.target}';`),'true');
 const directTarget=await targetClient(input);const ownedIdentity=JSON.parse(sql(`select json_build_object('userName',immutable_alias,'externalId',external_id) from outbound_scim_assignments where assignment_id='${assignment.id}';`));
 const late=await directTarget('POST','Users',{schemas:['urn:ietf:params:scim:schemas:core:2.0:User'],...ownedIdentity,userName:'late-'+randomUUID(),active:false,emails:[{value:'paused-outbound@example.test',type:'work',primary:true}]});assert.equal(late.status,409);checks.push('retired_reserved_incarnation_late_post_refused');
 const ordinaryEmail='ordinary-'+randomUUID()+'@example.test';const ordinary=await directTarget('POST','Users',{schemas:['urn:ietf:params:scim:schemas:core:2.0:User'],userName:'ordinary-'+randomUUID(),externalId:'ordinary-'+randomUUID(),active:false,emails:[{value:ordinaryEmail,type:'work',primary:true}]});assert.equal(ordinary.status,201);const ordinaryUser=JSON.parse(ordinary.body);assert.equal((await directTarget('DELETE','Users/'+ordinaryUser.id,undefined,ordinary.headers.etag)).status,204);assert.equal(targetSql(`select count(*) from users where tenant_id='target' and user_id='${ordinaryUser.id}' and email=${quote(ordinaryEmail)};`),'1');checks.push('ordinary_scim_delete_retains_email_while_reserved_delete_releases_it');
 stage='durable deletion archival';assignment=(await assignments()).find(a=>a.id===assignment.id);const archived=await lifecycle(assignment,'archive');assert.equal(archived.completed,true);checks.push('archive_completed_delete_receipt_without_new_remote_effect');
 stage='explicit fresh incarnation';const recreate=await lifecycle(assignment,'recreate');let replacement;await until(async()=>{const rows=(await jsonOk(await request('GET',base+'/assignments/'+assignment.id+'/lifecycle'))).items;const result=rows.find(r=>r.id===recreate.id);if(result?.completed){replacement=result.replacement;return true;}});const fresh=await settled(replacement);assert.notEqual(fresh.generation,assignment.generation);assert.notEqual(fresh.target,assignment.target);checks.push('explicit_recreate_uses_fresh_generation_and_uuid_preserving_history');
 stage='foreign source';assert.equal((await request('POST',base+'/assignments',{expected_revision:connector.revision,kind:'user',sources:[randomUUID()]})).status(),409);checks.push('absent_or_foreign_source_refused');
 assert.equal(sql("select count(*) from outbox o where tenant_id='e2e' and kind like 'outbound_scim.%' and exists(select 1 from jsonb_object_keys(o.payload) k where k not in ('assignment','generation','request'));"),'0');checks.push('durable_jobs_contain_only_closed_locator_ids');
 stage='actual outbound console';await page.goto(input.issuer+'/admin/#/outbound-scim');await page.getByRole('heading',{name:'Outbound provisioning',exact:true}).waitFor();await page.setViewportSize({width:390,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));checks.push('actual_console_mobile_no_horizontal_overflow');
 const logs=await readFile(input.relay_evidence,'utf8');assert(!logs.includes('assertion')&&!logs.includes('access_token')&&!logs.includes('changed-outbound'));const events=logs.trim().split('\n').filter(Boolean).map(JSON.parse);assert(events.some(e=>e.fault==='drop_after_commit'&&e.family==='Users'&&e.method==='POST'));assert(events.some(e=>e.fault==='drop_after_commit'&&e.method==='DELETE'));assert(events.some(e=>e.fault==='refuse'&&e.status===503));checks.push('actual_committed_faults_and_redacted_relay_evidence');
 console.log(JSON.stringify({checks,passed:checks.length,real_webauthn:true,real_fapi_dpop:true,production_egress_guard_unchanged:true,owned_databases_only:true}));await context.close();
}catch(error){console.error('OUTBOUND_SCIM_STAGE='+stage+(lastStatus===undefined?'':' HTTP_STATUS='+lastStatus)+(lastFailure?' FAILURE_CODE='+lastFailure:''));try{const summary=sql("select coalesce(json_agg(json_build_object('kind',kind,'state',state,'failure_code',failure_code,'dirty',dirty,'mapped',target_id is not null)),'[]'::json) from outbound_scim_assignments where tenant_id='e2e';");console.error('OUTBOUND_SCIM_STATE='+summary);const peer=(await readFile(input.relay_evidence,'utf8')).trim().split('\n').filter(Boolean).slice(-8).map(JSON.parse);console.error('OUTBOUND_SCIM_PEER='+JSON.stringify(peer));}catch{}if(typeof error.actual==='number'&&typeof error.expected==='number')console.error('OUTBOUND_SCIM_ASSERT='+error.actual+'/'+error.expected);if(error.message?.startsWith('OWN_SQL_ERROR='))console.error('OUTBOUND_SCIM_SQL='+error.message);process.exitCode=1;}
finally{await browser.close();await new Promise(resolve=>callbackServer.close(resolve));}
