import type { JSX } from 'react';
import YAML from 'yaml';
import { CodePanel } from './code-panel';

/** Highlight the controlled YAML generated by this view without injecting HTML. */
function highlightedYaml(line: string): JSX.Element {
  const match = /^(\s*(?:-\s+)?)([^:#][^:]*):(\s*)(.*)$/.exec(line);
  const value = match?.[4] ?? '';
  const valueClass = /^(?:true|false|null|-?\d+(?:\.\d+)?)$/.test(value) ? 'yaml-scalar' : 'yaml-value';
  return <>{match
    ? <>{match[1]}<span className="yaml-key">{match[2]}</span><span className="yaml-punctuation">:</span>{match[3]}<span className={valueClass}>{value}</span></>
    : <span className={line.startsWith('#') ? 'yaml-comment' : 'yaml-value'}>{line}</span>}</>;
}

/** Read-only Kubernetes examples rendered and copied in the same format. */
export function YamlView({ value, label, documents = false }: Readonly<{ value: unknown; label: string; documents?: boolean }>): JSX.Element {
  const source = documents && Array.isArray(value) && value.length > 0
    ? value.map(item => YAML.stringify(item, { lineWidth: 0 }).trimEnd()).join('\n---\n') + '\n'
    : YAML.stringify(value, { lineWidth: 0 });
  return <CodePanel source={source} label={label} language="YAML" renderLine={highlightedYaml} />;
}
