import type { JSX } from 'react';
import { CopyIcon } from 'lucide-react';
import YAML from 'yaml';
import { Button } from '../ui';
import { toast } from './ui/toast';

/** Highlight the controlled YAML generated by this view without injecting HTML. */
function highlightedYaml(source: string): JSX.Element[] {
  return source.split('\n').map((line, index) => {
    const match = /^(\s*(?:-\s+)?)([^:#][^:]*):(\s*)(.*)$/.exec(line);
    const value = match?.[4] ?? '';
    const valueClass = /^(?:true|false|null|-?\d+(?:\.\d+)?)$/.test(value) ? 'yaml-scalar' : 'yaml-value';
    return <span className="yaml-line" key={index}>{match
      ? <>{match[1]}<span className="yaml-key">{match[2]}</span><span className="yaml-punctuation">:</span>{match[3]}<span className={valueClass}>{value}</span></>
      : <span className={line.startsWith('#') ? 'yaml-comment' : 'yaml-value'}>{line}</span>}{'\n'}</span>;
  });
}

/** Read-only Kubernetes examples rendered and copied in the same format. */
export function YamlView({ value, label, documents = false }: Readonly<{ value: unknown; label: string; documents?: boolean }>): JSX.Element {
  const source = documents && Array.isArray(value) && value.length > 0
    ? value.map(item => YAML.stringify(item, { lineWidth: 0 }).trimEnd()).join('\n---\n') + '\n'
    : YAML.stringify(value, { lineWidth: 0 });
  const lines = source.trimEnd().split('\n').length;
  const copy = async (): Promise<void> => {
    try {
      await navigator.clipboard.writeText(source);
      toast.success('YAML copied');
    } catch {
      toast.error('Could not copy the YAML');
    }
  };
  return <div className="json-view">
    <div className="json-toolbar"><span className="muted">YAML · {lines} {lines === 1 ? 'line' : 'lines'}</span>
      <Button small onClick={() => void copy()} aria-label={`Copy ${label}`}><CopyIcon aria-hidden="true" />Copy YAML</Button>
    </div>
    <pre className="json-code yaml-code" tabIndex={0} role="region" aria-label={label}><code>{highlightedYaml(source)}</code></pre>
  </div>;
}
