apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: asterius-playground
resources:
- resources.yaml
configMapGenerator:
- name: playground-gateway
  files:
  - nginx.conf
- name: playground-portal
  files:
  - portal/index.html
  - portal/style.css
