//! SAML 2.0 primitives, deliberately separate from the HTTP SSO flow.
//!
//! The only accepted inbound XML is a small AuthnRequest envelope. Parsing
//! creates an untrusted value; a tenant's explicitly provisioned SP record
//! must then match its issuer and ACS exactly. An XML Signature in an inbound
//! request is rejected here, because accepting one requires ID-aware XML
//! canonicalization and reference verification. No caller can confuse this
//! parser with a signature verifier.
//!
//! Outbound metadata is rendered from typed values, then signed using the
//! exclusive canonical XML bytes generated by this module. Arbitrary caller
//! XML is never passed to the signer. The browser SSO and logout handlers,
//! persistent trust provisioning, replay reservation and key rotation are
//! separate work.

use aws_lc_rs::rand::SystemRandom;
use aws_lc_rs::signature::{RSA_PKCS1_SHA256, RsaKeyPair};
use base64::{Engine as _, engine::general_purpose::STANDARD};
use quick_xml::{Reader, events::Event};
use sha2::{Digest, Sha256};
use std::collections::HashMap;
use time::{Duration, OffsetDateTime, format_description::well_known::Rfc3339};
use url::Url;

const METADATA_NS: &str = "urn:oasis:names:tc:SAML:2.0:metadata";
const PROTOCOL_NS: &str = "urn:oasis:names:tc:SAML:2.0:protocol";
const ASSERTION_NS: &str = "urn:oasis:names:tc:SAML:2.0:assertion";
const XMLDSIG_NS: &str = "http://www.w3.org/2000/09/xmldsig#";
const HTTP_POST: &str = "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST";
const RSA_SHA256: &str = "http://www.w3.org/2001/04/xmldsig-more#rsa-sha256";
const SHA256: &str = "http://www.w3.org/2001/04/xmlenc#sha256";
const EXC_C14N: &str = "http://www.w3.org/2001/10/xml-exc-c14n#";
const ENVELOPED: &str = "http://www.w3.org/2000/09/xmldsig#enveloped-signature";
const MAX_XML: usize = 64 * 1024;
const MAX_DEPTH: usize = 16;

/// Uniform refusal for malformed XML and requests without explicit trust.
#[derive(Debug, Clone, Copy, PartialEq, Eq, thiserror::Error)]
#[error("SAML request is not trusted")]
pub struct UntrustedSaml;

/// An operator-provisioned SP. This contains no automatically discovered
/// endpoints: SAML responses may only go to this exact ACS.
#[derive(Debug, Clone)]
pub struct TrustedSp {
    entity_id: String,
    acs: String,
}

impl TrustedSp {
    /// Constructs an SP trust entry from operator-approved values.
    pub fn new(entity_id: &str, acs: &str) -> Result<Self, UntrustedSaml> {
        if entity_id.is_empty() || entity_id.len() > 1024 || !valid_xml_attr(entity_id) {
            return Err(UntrustedSaml);
        }
        let parsed = Url::parse(acs).map_err(|_| UntrustedSaml)?;
        if acs.len() > 2048
            || !valid_xml_attr(acs)
            || parsed.scheme() != "https"
            || parsed.host_str().is_none()
            || parsed.fragment().is_some()
            || parsed.username() != ""
            || parsed.password().is_some()
        {
            return Err(UntrustedSaml);
        }
        Ok(Self {
            entity_id: entity_id.to_owned(),
            acs: acs.to_owned(),
        })
    }

    /// The SP's exact SAML entity identifier.
    #[must_use]
    pub fn entity_id(&self) -> &str {
        &self.entity_id
    }

    /// The operator-pinned HTTP-POST assertion consumer.
    #[must_use]
    pub fn acs(&self) -> &str {
        &self.acs
    }
}

/// Explicit trust, partitioned by routed tenant.
#[derive(Debug, Default)]
pub struct SpTrust(HashMap<String, HashMap<String, TrustedSp>>);

impl SpTrust {
    /// Inserts a trusted SP; duplicate entity IDs are refused.
    pub fn insert(&mut self, tenant: &str, sp: TrustedSp) -> Result<(), UntrustedSaml> {
        if tenant.is_empty() {
            return Err(UntrustedSaml);
        }
        let entries = self.0.entry(tenant.to_owned()).or_default();
        if entries.contains_key(sp.entity_id()) {
            return Err(UntrustedSaml);
        }
        entries.insert(sp.entity_id.clone(), sp);
        Ok(())
    }

    /// Resolves an already-parsed request against the routed tenant.
    pub fn resolve<'a>(
        &'a self,
        tenant: &str,
        request: &UntrustedAuthnRequest,
    ) -> Result<&'a TrustedSp, UntrustedSaml> {
        let sp = self
            .0
            .get(tenant)
            .and_then(|entries| entries.get(&request.issuer))
            .ok_or(UntrustedSaml)?;
        if request.acs.as_deref().is_some_and(|acs| acs != sp.acs)
            || request
                .binding
                .as_deref()
                .is_some_and(|binding| binding != HTTP_POST)
        {
            return Err(UntrustedSaml);
        }
        Ok(sp)
    }
}

/// A parsed request, not an authenticated request. A future SSO handler must
/// enforce destination, freshness, replay and request-signing policy.
#[derive(Debug, Clone)]
pub struct UntrustedAuthnRequest {
    pub id: String,
    pub issuer: String,
    pub issued_at: OffsetDateTime,
    pub destination: Option<String>,
    pub acs: Option<String>,
    pub binding: Option<String>,
}

/// Reads only the expected AuthnRequest envelope, with strict byte/depth
/// limits and no DTD, entity, PI, CDATA or XML Signature processing.
pub fn parse_authn_request(xml: &[u8]) -> Result<UntrustedAuthnRequest, UntrustedSaml> {
    if xml.is_empty() || xml.len() > MAX_XML {
        return Err(UntrustedSaml);
    }
    let mut reader = Reader::from_reader(xml);
    reader.config_mut().check_end_names = true;
    let mut depth = 0usize;
    let mut root_seen = false;
    let mut issuer_seen = false;
    let mut issuer = String::new();
    let mut id = None;
    let mut issued_at = None;
    let mut destination = None;
    let mut acs = None;
    let mut binding = None;
    let mut root_namespaces = HashMap::new();
    loop {
        match reader.read_event().map_err(|_| UntrustedSaml)? {
            Event::Start(e) => {
                depth += 1;
                if depth > MAX_DEPTH {
                    return Err(UntrustedSaml);
                }
                let name = e.name().as_ref().to_owned();
                if depth == 1 {
                    if root_seen || local_name(&name) != "AuthnRequest" {
                        return Err(UntrustedSaml);
                    }
                    root_seen = true;
                    root_namespaces = namespaces(&e, &HashMap::new())?;
                    if namespace_of(&name, &root_namespaces) != Some(PROTOCOL_NS) {
                        return Err(UntrustedSaml);
                    }
                    only_attributes(
                        &e,
                        &[
                            "ID",
                            "Version",
                            "IssueInstant",
                            "Destination",
                            "AssertionConsumerServiceURL",
                            "ProtocolBinding",
                        ],
                    )?;
                    if attribute(&e, "Version")?.as_deref() != Some("2.0") {
                        return Err(UntrustedSaml);
                    }
                    issued_at = attribute(&e, "IssueInstant")?
                        .and_then(|value| OffsetDateTime::parse(&value, &Rfc3339).ok());
                    id = attribute(&e, "ID")?;
                    destination = attribute(&e, "Destination")?;
                    acs = attribute(&e, "AssertionConsumerServiceURL")?;
                    binding = attribute(&e, "ProtocolBinding")?;
                } else if depth == 2 {
                    if local_name(&name) != "Issuer" || issuer_seen {
                        return Err(UntrustedSaml);
                    }
                    issuer_seen = true;
                    only_attributes(&e, &[])?;
                    let issuer_namespaces = namespaces(&e, &root_namespaces)?;
                    if namespace_of(&name, &issuer_namespaces) != Some(ASSERTION_NS) {
                        return Err(UntrustedSaml);
                    }
                } else {
                    return Err(UntrustedSaml);
                }
            }
            Event::Text(e) => {
                let content = e.xml10_content();
                let value = quick_xml::escape::unescape(&content).map_err(|_| UntrustedSaml)?;
                if depth == 2 && issuer_seen && issuer.is_empty() {
                    issuer = value.into_owned();
                } else if !value.trim().is_empty() {
                    return Err(UntrustedSaml);
                }
            }
            Event::End(_) => {
                if depth == 0 {
                    return Err(UntrustedSaml);
                }
                depth -= 1;
            }
            Event::Eof => break,
            Event::Decl(_) => return Err(UntrustedSaml),
            Event::Empty(_)
            | Event::DocType(_)
            | Event::PI(_)
            | Event::CData(_)
            | Event::GeneralRef(_) => return Err(UntrustedSaml),
            Event::Comment(_) => return Err(UntrustedSaml),
        }
    }
    if !root_seen || depth != 0 || !issuer_seen || issuer.is_empty() || issuer.len() > 1024 {
        return Err(UntrustedSaml);
    }
    let id = id.ok_or(UntrustedSaml)?;
    let issued_at = issued_at.ok_or(UntrustedSaml)?;
    if !valid_xml_id(&id) {
        return Err(UntrustedSaml);
    }
    Ok(UntrustedAuthnRequest {
        id,
        issuer,
        issued_at,
        destination,
        acs,
        binding,
    })
}

fn local_name(name: &str) -> &str {
    name.rsplit(':').next().unwrap_or(name)
}

fn namespaces(
    e: &quick_xml::events::BytesStart<'_>,
    inherited: &HashMap<String, String>,
) -> Result<HashMap<String, String>, UntrustedSaml> {
    let mut found = inherited.clone();
    for attr in e.attributes() {
        let attr = attr.map_err(|_| UntrustedSaml)?;
        let key = attr.key.as_ref();
        if key == "xmlns" || key.starts_with("xmlns:") {
            let prefix = key.strip_prefix("xmlns:").unwrap_or("");
            let value = attr
                .normalized_value(quick_xml::XmlVersion::Explicit1_0)
                .map_err(|_| UntrustedSaml)?;
            found.insert(prefix.to_owned(), value.into_owned());
        }
    }
    Ok(found)
}

fn namespace_of<'a>(name: &str, namespaces: &'a HashMap<String, String>) -> Option<&'a str> {
    let prefix = name.split_once(':').map_or("", |(prefix, _)| prefix);
    namespaces.get(prefix).map(String::as_str)
}

fn only_attributes(
    e: &quick_xml::events::BytesStart<'_>,
    allowed: &[&str],
) -> Result<(), UntrustedSaml> {
    for attr in e.attributes() {
        let attr = attr.map_err(|_| UntrustedSaml)?;
        let key = attr.key.as_ref();
        if key != "xmlns" && !key.starts_with("xmlns:") && !allowed.contains(&key) {
            return Err(UntrustedSaml);
        }
    }
    Ok(())
}

fn attribute(
    e: &quick_xml::events::BytesStart<'_>,
    name: &str,
) -> Result<Option<String>, UntrustedSaml> {
    let mut value = None;
    for attr in e.attributes() {
        let attr = attr.map_err(|_| UntrustedSaml)?;
        if attr.key.as_ref() == name {
            if value.is_some() {
                return Err(UntrustedSaml);
            }
            value = Some(
                attr.normalized_value(quick_xml::XmlVersion::Explicit1_0)
                    .map_err(|_| UntrustedSaml)?
                    .into_owned(),
            );
        }
    }
    Ok(value)
}

fn valid_xml_id(value: &str) -> bool {
    value.len() <= 128
        && value.starts_with('_')
        && value
            .bytes()
            .all(|b| b.is_ascii_alphanumeric() || matches!(b, b'_' | b'-' | b'.'))
}

/// A tenant IdP's public metadata values. The signing certificate is
/// provisioned by the operator and must match the private key supplied to
/// `sign_metadata`; this module does not manufacture certificates.
#[derive(Debug, Clone)]
pub struct IdpMetadata<'a> {
    pub entity_id: &'a str,
    pub sso_redirect_url: &'a str,
    pub signing_certificate_der: &'a [u8],
}

/// Errors generated while constructing signed metadata.
#[derive(Debug, Clone, Copy, PartialEq, Eq, thiserror::Error)]
pub enum MetadataError {
    #[error("invalid SAML metadata input")]
    InvalidInput,
    #[error("SAML metadata signing failed")]
    SigningFailed,
}

/// Signs an IdP metadata EntityDescriptor with RSA-SHA256, enveloped
/// signature and exclusive canonicalization. Only this module's own fixed
/// serializer is signed; it never canonicalizes arbitrary inbound XML.
pub fn sign_metadata(
    metadata: &IdpMetadata<'_>,
    private_key_pkcs8: &[u8],
) -> Result<String, MetadataError> {
    if metadata.entity_id.is_empty()
        || metadata.entity_id.len() > 1024
        || !valid_xml_attr(metadata.entity_id)
        || metadata.signing_certificate_der.is_empty()
        || metadata.signing_certificate_der.len() > 16_384
        || metadata.sso_redirect_url.len() > 2048
        || !https_url(metadata.sso_redirect_url)
        || !valid_xml_attr(metadata.sso_redirect_url)
    {
        return Err(MetadataError::InvalidInput);
    }
    let entity = escape_attr(metadata.entity_id);
    let url = escape_attr(metadata.sso_redirect_url);
    let cert = STANDARD.encode(metadata.signing_certificate_der);
    // Namespace declarations are placed on the elements where they are
    // visibly used; attributes are in lexical order. Attribute escaping uses
    // precisely the XML C14N required escapes. With this fixed serializer,
    // unsigned bytes equal the exclusive canonical form after the enveloped
    // transform. Changes to serialization require checking that invariant
    // against an independent XML C14N implementation before deployment.
    let unsigned = format!(
        "<md:EntityDescriptor xmlns:md=\"{METADATA_NS}\" entityID=\"{entity}\"><md:IDPSSODescriptor protocolSupportEnumeration=\"{PROTOCOL_NS}\"><md:KeyDescriptor use=\"signing\"><ds:KeyInfo xmlns:ds=\"{XMLDSIG_NS}\"><ds:X509Data><ds:X509Certificate>{cert}</ds:X509Certificate></ds:X509Data></ds:KeyInfo></md:KeyDescriptor><md:SingleSignOnService Binding=\"urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect\" Location=\"{url}\"></md:SingleSignOnService></md:IDPSSODescriptor></md:EntityDescriptor>"
    );
    let split = unsigned.find('>').ok_or(MetadataError::SigningFailed)? + 1;
    sign_enveloped(&unsigned, split, "", private_key_pkcs8)
}

fn sign_enveloped(
    unsigned: &str,
    insertion: usize,
    reference: &str,
    private_key_pkcs8: &[u8],
) -> Result<String, MetadataError> {
    let key = RsaKeyPair::from_pkcs8(private_key_pkcs8).map_err(|_| MetadataError::InvalidInput)?;
    let digest = STANDARD.encode(Sha256::digest(unsigned.as_bytes()));
    let signed_info = format!(
        "<ds:SignedInfo xmlns:ds=\"{XMLDSIG_NS}\"><ds:CanonicalizationMethod Algorithm=\"{EXC_C14N}\"></ds:CanonicalizationMethod><ds:SignatureMethod Algorithm=\"{RSA_SHA256}\"></ds:SignatureMethod><ds:Reference URI=\"{reference}\"><ds:Transforms><ds:Transform Algorithm=\"{ENVELOPED}\"></ds:Transform><ds:Transform Algorithm=\"{EXC_C14N}\"></ds:Transform></ds:Transforms><ds:DigestMethod Algorithm=\"{SHA256}\"></ds:DigestMethod><ds:DigestValue>{digest}</ds:DigestValue></ds:Reference></ds:SignedInfo>"
    );
    let mut signature = vec![0_u8; key.public_modulus_len()];
    key.sign(
        &RSA_PKCS1_SHA256,
        &SystemRandom::new(),
        signed_info.as_bytes(),
        &mut signature,
    )
    .map_err(|_| MetadataError::SigningFailed)?;
    let signature = STANDARD.encode(signature);
    let xml_signature = format!(
        "<ds:Signature xmlns:ds=\"{XMLDSIG_NS}\">{signed_info}<ds:SignatureValue>{signature}</ds:SignatureValue></ds:Signature>"
    );
    Ok(format!(
        "{}{xml_signature}{}",
        &unsigned[..insertion],
        &unsigned[insertion..]
    ))
}

/// Inputs for one bearer assertion. The caller must reserve the ID against
/// replay and must issue it only after the account owner's session and the SP
/// trust have been established. This type does not authorize issuance.
#[derive(Debug, Clone)]
pub struct Assertion<'a> {
    pub id: &'a str,
    pub issuer: &'a str,
    pub subject: &'a str,
    pub audience: &'a str,
    pub recipient: &'a str,
    pub in_response_to: &'a str,
    pub session_index: &'a str,
    pub authn_context_class_ref: &'a str,
    pub authenticated_at: OffsetDateTime,
    pub issued_at: OffsetDateTime,
    pub expires_at: OffsetDateTime,
}

/// Signs one module-built assertion using the IdP's RSA-SHA256 key. The
/// certificate must be published by a later IdP metadata route; XML KeyInfo
/// cannot itself establish trust.
pub fn sign_assertion(
    assertion: &Assertion<'_>,
    private_key_pkcs8: &[u8],
) -> Result<String, MetadataError> {
    if !valid_xml_id(assertion.id)
        || !valid_xml_id(assertion.in_response_to)
        || !valid_xml_id(assertion.session_index)
        || ![assertion.issuer, assertion.subject, assertion.audience]
            .iter()
            .all(|v| !v.is_empty() && v.len() <= 1024 && valid_xml_attr(v))
        || assertion.recipient.len() > 2048
        || !https_url(assertion.recipient)
        || !valid_xml_attr(assertion.recipient)
        || assertion.authn_context_class_ref.is_empty()
        || assertion.authn_context_class_ref.len() > 1024
        || !valid_xml_attr(assertion.authn_context_class_ref)
        || assertion.authenticated_at > assertion.issued_at
        || assertion.expires_at <= assertion.issued_at
        || assertion.expires_at - assertion.issued_at > Duration::minutes(5)
    {
        return Err(MetadataError::InvalidInput);
    }
    let issued = assertion
        .issued_at
        .format(&Rfc3339)
        .map_err(|_| MetadataError::InvalidInput)?;
    let expires = assertion
        .expires_at
        .format(&Rfc3339)
        .map_err(|_| MetadataError::InvalidInput)?;
    let authenticated = assertion
        .authenticated_at
        .format(&Rfc3339)
        .map_err(|_| MetadataError::InvalidInput)?;
    let id = escape_attr(assertion.id);
    let issuer = escape_text(assertion.issuer);
    let subject = escape_text(assertion.subject);
    let audience = escape_text(assertion.audience);
    let recipient = escape_attr(assertion.recipient);
    let request = escape_attr(assertion.in_response_to);
    let session = escape_attr(assertion.session_index);
    let authn_context = escape_text(assertion.authn_context_class_ref);
    let issuer_element = format!("<saml:Issuer>{issuer}</saml:Issuer>");
    let unsigned = format!(
        "<saml:Assertion xmlns:saml=\"{ASSERTION_NS}\" ID=\"{id}\" IssueInstant=\"{issued}\" Version=\"2.0\">{issuer_element}<saml:Subject><saml:NameID>{subject}</saml:NameID><saml:SubjectConfirmation Method=\"urn:oasis:names:tc:SAML:2.0:cm:bearer\"><saml:SubjectConfirmationData InResponseTo=\"{request}\" NotOnOrAfter=\"{expires}\" Recipient=\"{recipient}\"></saml:SubjectConfirmationData></saml:SubjectConfirmation></saml:Subject><saml:Conditions NotBefore=\"{issued}\" NotOnOrAfter=\"{expires}\"><saml:AudienceRestriction><saml:Audience>{audience}</saml:Audience></saml:AudienceRestriction></saml:Conditions><saml:AuthnStatement AuthnInstant=\"{authenticated}\" SessionIndex=\"{session}\"><saml:AuthnContext><saml:AuthnContextClassRef>{authn_context}</saml:AuthnContextClassRef></saml:AuthnContext></saml:AuthnStatement></saml:Assertion>"
    );
    let insertion = unsigned
        .find(&issuer_element)
        .ok_or(MetadataError::SigningFailed)?
        + issuer_element.len();
    sign_enveloped(&unsigned, insertion, &format!("#{id}"), private_key_pkcs8)
}

/// Builds a SAML HTTP-POST success Response containing one signed bearer
/// assertion. Its envelope is derived exclusively from that assertion: the
/// response and assertion carry the same issuer, request ID and ACS URL.
/// No caller-supplied unsigned envelope field can redirect a signed assertion
/// to a different SP. The Response itself is unsigned; the assertion is the
/// integrity-protected object required for the POST binding.
///
/// This is an internal serializer, not authorization to issue an assertion.
/// A future SSO route must establish an authenticated session, check the
/// original validated request and trusted SP, and provision a dedicated IdP
/// signing key before it calls this function.
pub fn build_post_response(
    response_id: &str,
    assertion: &Assertion<'_>,
    private_key_pkcs8: &[u8],
) -> Result<String, MetadataError> {
    if !valid_xml_id(response_id)
        || response_id == assertion.id
        || response_id == assertion.in_response_to
    {
        return Err(MetadataError::InvalidInput);
    }
    let signed_assertion = sign_assertion(assertion, private_key_pkcs8)?;
    let issued = assertion
        .issued_at
        .format(&Rfc3339)
        .map_err(|_| MetadataError::InvalidInput)?;
    let id = escape_attr(response_id);
    let request = escape_attr(assertion.in_response_to);
    let destination = escape_attr(assertion.recipient);
    let issuer = escape_text(assertion.issuer);
    Ok(format!(
        "<samlp:Response xmlns:samlp=\"{PROTOCOL_NS}\" ID=\"{id}\" InResponseTo=\"{request}\" Version=\"2.0\" IssueInstant=\"{issued}\" Destination=\"{destination}\"><saml:Issuer xmlns:saml=\"{ASSERTION_NS}\">{issuer}</saml:Issuer><samlp:Status><samlp:StatusCode Value=\"urn:oasis:names:tc:SAML:2.0:status:Success\"></samlp:StatusCode></samlp:Status>{signed_assertion}</samlp:Response>"
    ))
}

fn https_url(value: &str) -> bool {
    Url::parse(value).is_ok_and(|url| {
        url.scheme() == "https"
            && url.host_str().is_some()
            && url.username().is_empty()
            && url.password().is_none()
            && url.fragment().is_none()
    })
}

fn valid_xml_attr(value: &str) -> bool {
    value.chars().all(|ch| {
        let code = ch as u32;
        code >= 0x20 && code != 0xFFFE && code != 0xFFFF
    })
}

fn escape_attr(value: &str) -> String {
    let mut out = String::with_capacity(value.len());
    for ch in value.chars() {
        match ch {
            '&' => out.push_str("&amp;"),
            '<' => out.push_str("&lt;"),
            '"' => out.push_str("&quot;"),
            '\r' => out.push_str("&#xD;"),
            '\n' => out.push_str("&#xA;"),
            '\t' => out.push_str("&#x9;"),
            _ => out.push(ch),
        }
    }
    out
}

fn escape_text(value: &str) -> String {
    let mut out = String::with_capacity(value.len());
    for ch in value.chars() {
        match ch {
            '&' => out.push_str("&amp;"),
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            '\r' => out.push_str("&#xD;"),
            _ => out.push(ch),
        }
    }
    out
}
