import {
  AppWindowIcon,
  BoxesIcon,
  FlaskConicalIcon,
  ClipboardCheckIcon,
  FileSearchIcon,
  HeartPulseIcon,
  SendIcon,
  ShieldPlusIcon,
  Building2Icon,
  KeyRoundIcon,
  LayoutDashboardIcon,
  RadioIcon,
  ServerIcon,
  ScaleIcon,
  ShieldCheckIcon,
  ScrollTextIcon,
  ShapesIcon,
  PaletteIcon,
  UsersRoundIcon,
  Settings2Icon,
  SlidersHorizontalIcon,
  UsersIcon,
  BookOpenIcon,
  MailIcon,
  NetworkIcon,
  RefreshCwIcon,
  WaypointsIcon,
} from 'lucide-react';
import type { LucideIcon } from 'lucide-react';

/** Owned route symbols shared by navigation, overview shortcuts and page illustrations. */
export const NAVIGATION_ICONS: Readonly<Record<string, LucideIcon>> = {
  overview: LayoutDashboardIcon,
  users: UsersIcon,
  groups: UsersRoundIcon,
  roles: ShieldCheckIcon,
  'temporary-privileges': ShieldPlusIcon,
  'access-reviews': ClipboardCheckIcon,
  'governance-findings': FileSearchIcon,
  clients: AppWindowIcon,
  resources: ServerIcon,
  architecture: NetworkIcon,
  'authorization-details': ShapesIcon,
  keys: KeyRoundIcon,
  'token-console': FlaskConicalIcon,
  kubernetes: BoxesIcon,
  policy: ScaleIcon,
  ssf: RadioIcon,
  audit: ScrollTextIcon,
  tenants: Building2Icon,
  settings: SlidersHorizontalIcon,
  branding: PaletteIcon,
  preferences: Settings2Icon,
  scim: RefreshCwIcon,
  'outbound-scim': SendIcon,
  health: HeartPulseIcon,
  federation: NetworkIcon,
  'oidc-providers': WaypointsIcon,
  saml: WaypointsIcon,
  mail: MailIcon,
  help: BookOpenIcon,
};
