/**
 * The tenants screen (`ast-l5bl`).
 *
 * The one screen in this console that is about the *deployment* rather than
 * about a tenant: it lists every tenant this server serves, creates one, and
 * suspends or restores one. Its navigation entry declares
 * `reach: 'deployment'` (`navigation.ts`), so a tenant admin never sees the
 * link — and every route below re-checks the same authority, because a hidden
 * link is a courtesy and not a control.
 *
 * # What it does not invent
 *
 * `GET /tenants` answers with what `summarise` in
 * `crates/admin-api/src/router.rs` renders: an id, an issuer, a display name,
 * a default resource, an optional custom host and a status. There is no count
 * of clients and no count of users in that document, so there is no column for
 * either one here: a console that showed "—" under a heading it invented would
 * be describing an API that does not exist.
 *
 * Features are a second document — `GET /tenants/{tenant_id}/settings`, which
 * a deployment-scoped caller may read for any tenant — so the column is filled
 * in by one read per listed row, after the list has drawn. Tens of tenants is
 * what the server's own pagination note expects (`list_tenants`), and a read
 * that fails leaves one cell unknown rather than failing the screen. The
 * alternative, widening the list document with every tenant's flags, is a
 * change to a route four screens depend on and is noted as follow-up rather
 * than made here.
 *
 * # What creating a tenant asks for
 *
 * Exactly what `POST /tenants` requires and nothing more. The signing keys are
 * generated by the server in the same step as the row (`ast-qa3`,
 * `ProvisionedTenants`), so there is no key material to ask an operator for —
 * a form with a "public key" box would be a form that cannot be filled in.
 * Features are *not* settable at creation because the creation route does not
 * take them; the form says where they are set instead of pretending.
 */
import { useCallback, useEffect, useState } from 'react';
import type { JSX } from 'react';
import { type Session, mutate, read } from './api';
import { hrefOf } from './routes';
import { type Settings, settingsPath } from './settings';
import {
  Actions,
  Badge,
  Button,
  ConfirmDialog,
  DataTable,
  EmptyState,
  Field,
  LoadFailure,
  Message,
  Panel,
  Screen,
  Skeleton,
} from './ui';

/** Whether a tenant is served at all, as the API spells it. */
export type TenantStatus = 'active' | 'disabled';

/** One tenant, as `GET /tenants` describes it. */
export interface TenantRow {
  readonly tenant_id: string;
  readonly issuer: string;
  readonly display_name: string;
  readonly default_resource: string;
  readonly custom_host: string | null;
  readonly status: TenantStatus;
}

/** One page of them. */
export interface TenantPage {
  readonly items: readonly TenantRow[];
  readonly next_cursor: string | null;
}

/** What a load is doing. */
type Load =
  | { readonly kind: 'loading' }
  | { readonly kind: 'ready'; readonly value: TenantPage }
  | { readonly kind: 'failed'; readonly message: string };

/** What the confirmation dialog is about, when one is open. */
interface Pending {
  readonly tenant: TenantRow;
  readonly enable: boolean;
}

function failure(error: unknown, fallback: string): string {
  return error instanceof Error ? error.message : fallback;
}

/**
 * Whether this session may create a tenant or change one's status.
 *
 * `deployment_scopes` and not `scopes`: a tenant admin holding
 * `admin.tenants:write` over their own tenant may save that tenant's settings
 * and may not touch the deployment's list of them. The two lists are kept
 * apart by `GET /session` for exactly this distinction (`navigation.ts`).
 */
export function mayWrite(session: Session): boolean {
  return session.deployment_scopes.includes('admin.tenants:write');
}

/** The path of one tenant's status, relative to the API base. */
export function statusPath(tenant: string): string {
  return `tenants/${encodeURIComponent(tenant)}/status`;
}

/**
 * Where this tenant's own console is.
 *
 * Built from the issuer and from nothing else. The console is mounted under
 * the tenant it belongs to — `/t/{id}/admin/`, or the root of a custom host —
 * and the issuer is the one value this document carries that names that
 * origin and that prefix together (`crates/server/src/http/console.rs`). A URL
 * assembled from the tenant id and this page's own location would be wrong for
 * every tenant reached through a custom host.
 */
export function tenantConsoleUrl(issuer: string, route: string): string {
  return `${issuer.replace(/\/+$/, '')}/admin/#/${route}`;
}

/**
 * What the features cell says.
 *
 * The settings document reports what is *off*, so that is what is rendered:
 * "everything on" is the ordinary case and deserves the short sentence, and a
 * list of names is the exception worth reading. Naming the flags this build
 * knows about and calling the rest "on" would be a claim about the server's
 * feature set that this bundle is not entitled to make.
 */
export function describeFeatures(disabled: readonly string[] | undefined): string {
  if (disabled === undefined) {
    return '—';
  }
  return disabled.length === 0 ? 'all on' : `off: ${[...disabled].sort().join(', ')}`;
}

/**
 * Which creation field the server's refusal is about, when it is about one.
 *
 * The refusal envelope carries a sentence and no JSON pointer
 * (`crates/admin-api/src/error.rs`), so the only honest thing to read is the
 * prefix the handler writes: `create_tenant` refuses with `tenant_id: …` or
 * `issuer: …`, and refuses a name already taken with "tenant … already
 * exists". Anything else maps to no field, because a guess would mark the
 * wrong one.
 */
export function refusedField(message: string | null): 'tenant_id' | 'issuer' | null {
  if (message === null) {
    return null;
  }
  if (message.startsWith('tenant_id:') || message.includes('already exists')) {
    return 'tenant_id';
  }
  if (message.startsWith('issuer:')) {
    return 'issuer';
  }
  return null;
}

export function Tenants({ session }: { session: Session }): JSX.Element {
  const [load, setLoad] = useState<Load>({ kind: 'loading' });
  const [cursor, setCursor] = useState<string | null>(null);
  const [features, setFeatures] = useState<Record<string, readonly string[]>>({});
  const [notice, setNotice] = useState<string | null>(null);
  const [refusal, setRefusal] = useState<string | null>(null);
  const [pending, setPending] = useState<Pending | null>(null);
  const [busy, setBusy] = useState(false);

  const refresh = useCallback((from: string | null) => {
    setLoad({ kind: 'loading' });
    read(from === null ? 'tenants' : `tenants?cursor=${encodeURIComponent(from)}`).then(
      (value) => setLoad({ kind: 'ready', value: value as TenantPage }),
      (error: unknown) =>
        setLoad({ kind: 'failed', message: failure(error, 'the tenants could not be read') }),
    );
  }, []);

  useEffect(() => refresh(cursor), [refresh, cursor]);

  // One settings read per listed tenant, after the list is on screen. The
  // flag says whether the page this effect belongs to is still the one being
  // shown: a click on "Next page" while six reads are in flight must not
  // write their answers into the new page's state.
  useEffect(() => {
    if (load.kind !== 'ready') {
      return undefined;
    }
    let live = true;
    for (const row of load.value.items) {
      read(settingsPath(row.tenant_id)).then(
        (document) => {
          if (!live) {
            return;
          }
          const settings = document as Settings;
          setFeatures((held) => ({ ...held, [row.tenant_id]: settings.disabled_features }));
        },
        // A settings read that is refused leaves that one cell unknown. The
        // list is the screen; failing all of it because one tenant's flags
        // could not be read would be the wrong trade.
        () => undefined,
      );
    }
    return () => {
      live = false;
    };
  }, [load]);

  const changeStatus = useCallback(
    (subject: Pending) => {
      setBusy(true);
      setRefusal(null);
      setNotice(null);
      mutate(statusPath(subject.tenant.tenant_id), 'PUT', session, {
        enabled: subject.enable,
      }).then(
        () => {
          setBusy(false);
          setPending(null);
          setNotice(
            subject.enable
              ? `${subject.tenant.tenant_id} is serving again.`
              : `${subject.tenant.tenant_id} is suspended. Every client and every user of it is now refused.`,
          );
          refresh(cursor);
        },
        (error: unknown) => {
          setBusy(false);
          setPending(null);
          setRefusal(failure(error, 'the change was refused'));
        },
      );
    },
    [cursor, refresh, session],
  );

  const writable = mayWrite(session);

  return (
    <Screen
      title="Tenants"
      description="Every tenant this deployment serves. Suspending one stops it answering at every endpoint, for every client and every user it has."
    >
      {notice !== null && <Message tone="success">{notice}</Message>}
      {refusal !== null && <Message tone="error">{refusal}</Message>}

      <Panel
        title="Directory"
        description="One page at a time, in the order the server returns. Features come from each tenant's own settings document."
      >
        {load.kind === 'loading' && <Skeleton rows={4} label="Reading the tenants." />}
        {load.kind === 'failed' && (
          <LoadFailure message={load.message} onRetry={() => refresh(cursor)} />
        )}
        {load.kind === 'ready' && (
          <>
            <TenantTable
              rows={load.value.items}
              features={features}
              writable={writable}
              onChange={(tenant, enable) => setPending({ tenant, enable })}
            />
            <Actions>
              <Button disabled={cursor === null} onClick={() => setCursor(null)}>
                First page
              </Button>
              <Button
                disabled={load.value.next_cursor === null}
                onClick={() => setCursor(load.value.next_cursor)}
              >
                Next page
              </Button>
            </Actions>
          </>
        )}
      </Panel>

      {writable && (
        <NewTenant
          session={session}
          onCreated={(created) => {
            setRefusal(null);
            setNotice(`${created.tenant_id} was created, with its signing keys.`);
            setCursor(null);
            refresh(null);
          }}
        />
      )}

      {pending !== null && (
        <ConfirmDialog
          title={pending.enable ? 'Restore this tenant?' : 'Suspend this tenant?'}
          body={
            pending.enable
              ? `${pending.tenant.tenant_id} will answer at ${pending.tenant.issuer} again, for every client and every user it has.`
              : `${pending.tenant.tenant_id} will stop answering at ${pending.tenant.issuer}. Every client of it fails to obtain a token and every user of it fails to sign in, including its own administrators. Nothing is deleted, and restoring it here undoes this.`
          }
          confirmLabel={pending.enable ? 'Restore tenant' : 'Suspend tenant'}
          busy={busy}
          onConfirm={() => changeStatus(pending)}
          onCancel={() => setPending(null)}
        />
      )}
    </Screen>
  );
}

/** The list, with what can be done to each row. */
function TenantTable({
  rows,
  features,
  writable,
  onChange,
}: {
  rows: readonly TenantRow[];
  features: Record<string, readonly string[]>;
  writable: boolean;
  onChange: (tenant: TenantRow, enable: boolean) => void;
}): JSX.Element {
  return (
    <DataTable
      caption="Tenants"
      rows={rows}
      rowKey={(row) => row.tenant_id}
      empty={
        <EmptyState
          title="This deployment serves no tenant yet."
          body="Create one below. It is given its signing keys in the same step."
        />
      }
      columns={[
        {
          key: 'tenant_id',
          header: 'Tenant',
          sortBy: (row) => row.tenant_id,
          cell: (row) => (
            <>
              <strong>{row.tenant_id}</strong>
              {row.display_name !== row.tenant_id && (
                <>
                  {' '}
                  <span className="muted">{row.display_name}</span>
                </>
              )}
            </>
          ),
        },
        {
          key: 'issuer',
          header: 'Issuer',
          sortBy: (row) => row.issuer,
          cell: (row) => <span className="wrap-anywhere">{row.issuer}</span>,
        },
        {
          key: 'status',
          header: 'Status',
          sortBy: (row) => row.status,
          cell: (row) => (
            <Badge tone={row.status === 'active' ? 'ok' : 'bad'}>{row.status}</Badge>
          ),
        },
        {
          key: 'features',
          header: 'Features',
          cell: (row) => describeFeatures(features[row.tenant_id]),
        },
        {
          key: 'links',
          header: 'Where to go',
          cell: (row) => (
            <span className="row">
              {/* The settings screen, pointed at this tenant. The admin API's
                  settings routes name their tenant in the path and admit a
                  deployment-scoped caller for any of them, so this is a screen
                  that works rather than a link that 403s. */}
              <a href={hrefOf('settings', { tenant: row.tenant_id })}>Settings</a>
              {/* The clients screen, on the *other* side: `GET /clients` has no
                  tenant in its path and serves the tenant the request was
                  routed to, so this tenant's clients are administered from this
                  tenant's own console and not from here. The link says where
                  that is; a session there is a session of that tenant. */}
              <a href={tenantConsoleUrl(row.issuer, 'clients')}>Clients</a>
            </span>
          ),
        },
        ...(writable
          ? [
              {
                key: 'status-change',
                header: 'Actions',
                actions: true,
                cell: (row: TenantRow) => (
                  <Button
                    small
                    variant={row.status === 'active' ? 'danger' : 'secondary'}
                    onClick={() => onChange(row, row.status !== 'active')}
                  >
                    {row.status === 'active' ? 'Suspend' : 'Restore'}
                  </Button>
                ),
              },
            ]
          : []),
      ]}
    />
  );
}

/**
 * The creation form.
 *
 * Five fields, two of them required, and every one of them a member
 * `POST /tenants` accepts. The server checks all of them again — the id and
 * the issuer are parsed by the domain's own types — and a refusal is shown
 * beside the field it names, with the server's sentence kept verbatim at the
 * top because that sentence is the one worth reading.
 */
function NewTenant({
  session,
  onCreated,
}: {
  session: Session;
  onCreated: (created: TenantRow) => void;
}): JSX.Element {
  const [id, setId] = useState('');
  const [issuer, setIssuer] = useState('');
  const [displayName, setDisplayName] = useState('');
  const [resource, setResource] = useState('');
  const [host, setHost] = useState('');
  const [busy, setBusy] = useState(false);
  const [refusal, setRefusal] = useState<string | null>(null);

  const submit = (event: React.FormEvent): void => {
    event.preventDefault();
    setBusy(true);
    setRefusal(null);
    const body: Record<string, unknown> = {
      tenant_id: id.trim(),
      issuer: issuer.trim(),
    };
    if (displayName.trim() !== '') {
      body.display_name = displayName.trim();
    }
    if (resource.trim() !== '') {
      body.default_resource = resource.trim();
    }
    if (host.trim() !== '') {
      body.custom_host = host.trim();
    }
    mutate('tenants', 'POST', session, body).then(
      (created) => {
        setBusy(false);
        setId('');
        setIssuer('');
        setDisplayName('');
        setResource('');
        setHost('');
        onCreated(created as TenantRow);
      },
      (error: unknown) => {
        setBusy(false);
        setRefusal(failure(error, 'the tenant was refused'));
      },
    );
  };

  const refused = refusedField(refusal);
  const mark = 'This is the value the server refused above.';

  return (
    <Panel
      id="new-tenant"
      title="Add a tenant"
      description="The server generates this tenant's signing keys in the same step, so there is no key material to supply. Its features and lifetimes are set afterwards, on its settings screen."
    >
      {refusal !== null && <Message tone="error">{refusal}</Message>}
      <form onSubmit={submit}>
        <Field
          label="Tenant id"
          required
          hint="Lowercase, and part of every URL this tenant is reached at. It cannot be changed afterwards."
          error={refused === 'tenant_id' ? mark : null}
        >
          {(props) => (
            <input
              {...props}
              name="tenant_id"
              value={id}
              onChange={(event) => setId(event.target.value)}
            />
          )}
        </Field>
        <Field
          label="Issuer"
          required
          hint="The https URL this tenant identifies itself by, with no trailing slash (RFC 8414 §2)."
          error={refused === 'issuer' ? mark : null}
        >
          {(props) => (
            <input
              {...props}
              name="issuer"
              type="url"
              value={issuer}
              onChange={(event) => setIssuer(event.target.value)}
            />
          )}
        </Field>
        <Field label="Display name" hint="What people call it. The tenant id is used when this is empty.">
          {(props) => (
            <input
              {...props}
              name="display_name"
              value={displayName}
              onChange={(event) => setDisplayName(event.target.value)}
            />
          )}
        </Field>
        <Field
          label="Default resource"
          hint="The audience a token is issued for when a request names none. The issuer is used when this is empty."
        >
          {(props) => (
            <input
              {...props}
              name="default_resource"
              value={resource}
              onChange={(event) => setResource(event.target.value)}
            />
          )}
        </Field>
        <Field label="Custom host" hint="A host this tenant is also reached at, instead of the /t/ prefix.">
          {(props) => (
            <input
              {...props}
              name="custom_host"
              value={host}
              onChange={(event) => setHost(event.target.value)}
            />
          )}
        </Field>
        <Actions>
          <Button type="submit" variant="primary" disabled={busy}>
            Create tenant
          </Button>
        </Actions>
      </form>
    </Panel>
  );
}
